window.translations = {
    en: {
        APP_TITLE: "ApexDeco",
        CHART_NO_HE: "No helium in this dive — nothing to off-gas.",
        CHART_SUPERSAT_TITLE: "Gas Tension in Tissue Compartments",
        CHART_MODE_SUPERSAT: "SuperSat",
        CHART_MODE_N2: "N2 offgas",
        CHART_MODE_HE: "He offgas",
        CHART_MODE_SURF: "Surface offgas",
        CHART_TITLE_SUPERSAT: "Tissue super-saturation: total Ptis - Pamb",
        CHART_TITLE_N2: "N2 off-gas gradient: pN2 - pAlv*fN2",
        CHART_TITLE_HE: "He off-gas gradient: pHe",
        CHART_TITLE_SURF: "Surface off-gas: total Ptis - Psurf",
        CHART_X_RUNTIME: "Runtime (min)",
        CHART_COMP_MAX: "Max",
        CHART_COMP_ALL: "All",
        BTN_NAV_PLAN: "Plan",
        BTN_NAV_HELP: "Help",
        BTN_NAV_SETTINGS: "Settings",
        BTN_NAV_TOOLS: "Tools",
        CARD_BOTTOM_MIX: "Bottom Mix & Travel",
        CARD_DECO_MIXES: "Deco Mixes",
        BTN_ADD_LEVEL: "+ Add Level",
        BTN_ADD_DECO: "+ Add Deco",
        BTN_DELETE: "Delete",
        BTN_CALCULATE: "Calculate",
        BTN_RESET_TISSUES: "Reset surface tissues",
        MSG_NO_BOTTOM_LEVELS: "No bottom levels. Click + Add Level.",
        MSG_NO_DECO_MIXES: "No deco mixes. Click + Add Deco.",
        MODAL_TITLE_ADD_LEVEL: "Add Bottom Mix & Travel",
        MODAL_TITLE_EDIT_LEVEL: "Edit Bottom Mix & Travel",
        MODAL_TITLE_ADD_DECO: "Add Deco Mix",
        MODAL_TITLE_EDIT_DECO: "Edit Deco Mix",
        LABEL_DEPTH: "Depth",
        LABEL_TIME_MIN: "Time (min)",
        LABEL_O2_PERCENT: "O2 %",
        LABEL_HE_PERCENT: "He %",
        LABEL_DEPTH_CHANGE_OVERRIDE: "Depth change override",
        LABEL_SETPOINT: "Setpoint",
        LABEL_OC_OR_SCR: "OC or SCR Leg:",
        BTN_SAVE: "Save",
        BTN_CANCEL: "Cancel",
        BTN_OK: "OK",
        BTN_COPY: "Copy",
        BTN_CLOSE: "Close",
        ERR_O2_HE_EXCEED: "O2 + He cannot exceed 100%",
        ERR_INVALID_DECO_SWITCH_DEPTH: "Enter a valid deco switch depth.",
        CARD_APPEARANCE: "Appearance",
        LABEL_LANGUAGE: "Language",
        LABEL_INTERFACE_STYLE: "Interface Style",
        OPT_LIGHT_THEME: "Light Theme",
        OPT_DARK_THEME: "Dark Theme",
        CARD_MODEL_SETTINGS: "Model Settings",
        LABEL_CIRCUIT: "Circuit",
        OPT_OC: "OC",
        OPT_CCR: "CCR",
        LABEL_DECO_MODEL: "Deco Model",
        LABEL_CONSERVATISM: "Conservatism",
        LABEL_GF_LO: "GF Lo",
        LABEL_GF_HI: "GF Hi",
        LABEL_O2_NARCOTIC: "O2 Narcotic",
        OPT_YES: "Yes",
        OPT_NO: "No",
        CARD_UNIT_SETTINGS: "Unit Settings",
        LABEL_DEPTH_UNITS: "Depth Units",
        OPT_METER: "Meter",
        OPT_FEET: "Feet",
        LABEL_WATER_TYPE: "Water Type",
        OPT_SALT: "Salt",
        OPT_FRESH: "Fresh",
        LABEL_ALTITUDE: "Altitude (m)",
        LABEL_ACCLIMATIZED: "Acclimatized (m)",
        LABEL_GAS_VOLUME: "Gas Volume",
        OPT_LITER: "Liter",
        OPT_CUFT: "CuFt",
        LABEL_PRESSURE_UNITS: "Pressure Units",
        LABEL_GAUGE_TYPE: "Gauge Type",
        OPT_SIMPLE: "Simple",
        OPT_DIGITAL: "Digital",
        LABEL_TEMPERATURE: "Temperature",
        CARD_RATES: "Descent / Ascent Rates",
        LABEL_DESCENT_RATE: "Descent Rate",
        LABEL_ASCENT_RATE: "Ascent Rate",
        LABEL_DECO_ASCENT_RATE: "Deco Ascent Rate",
        LABEL_SURFACE_ASCENT_RATE: "Surface Ascent Rate",
        CARD_DECO_STOPS: "Deco Stop Settings",
        LABEL_STEP_SIZE: "Step Size",
        LABEL_LAST_STOP_OC: "Last Stop (OC)",
        LABEL_LAST_STOP_CCR: "Last Stop (CCR)",
        LABEL_MIN_STOP_TIME: "Min Stop Time",
        OPT_STOP_1MIN: "1 min",
        OPT_STOP_30S: "30 sec",
        OPT_STOP_10S: "10 sec",
        OPT_STOP_1S: "1 sec",
        LABEL_PPO2_SWAP: "ppO2 Deco Swap",
        LABEL_PPO2_MID_MIX: "ppO2 28-45% mix",
        LABEL_PPO2_HIGH_MIX: "ppO2 45-99% mix",
        LABEL_PPO2_BOTTOM_MAX: "ppO2 Bottom Max",
        LABEL_O2_MAX_DEPTH: "O2 100% Max Depth",
        LABEL_FIRST_STOP_30S: "First Stop 30sec",
        LABEL_FIRST_STOP_DBL: "First Stop Double Step",
        OPT_OFF: "Off",
        OPT_ON: "On",
        CARD_CCR_SETTINGS: "CCR Settings",
        LABEL_DEFAULT_SETPOINT: "Default Setpoint",
        LABEL_SP_UNITS: "SP Units",
        CARD_RMV: "RMV / Gas Planning",
        LABEL_BOTTOM_RMV: "Bottom RMV",
        LABEL_DECO_RMV: "Deco RMV",
        LABEL_CCR_DIL_RMV: "CCR Dil Metabolic",
        CARD_EXTENDED_STOPS: "Extended Stops",
        LABEL_EXTENDED_STOPS: "Extended Stops",
        LABEL_ADD_TIME_STOP: "Add time to stop",
        LABEL_ALL_MIX_CHANGES: "All mix changes",
        LABEL_O2_WINDOW: "O2 window effect",
        MSG_EXT_STOPS_DESC: "Include extended stops with deco mix swaps",
        LABEL_EXT_SHALLOW: "7..30 m",
        LABEL_EXT_DEEP: "30 + m",
        CARD_WARNINGS: "Warning Thresholds",
        LABEL_WARN_PPO2_HI: "ppO2 High",
        LABEL_WARN_PPO2_LO: "ppO2 Low",
        LABEL_WARN_CNS: "CNS % above",
        LABEL_WARN_OTU: "OTU's above",
        LABEL_WARN_IBCD_N2: "IBCD N2",
        LABEL_WARN_IBCD_HE: "IBCD He",
        LABEL_WARN_CCR_DIL: "CCR diluent check",
        MSG_CCR_DIL_CHECK: "Check diluent ppO2 vs setpoint",
        CARD_BAILOUT: "Bailout Settings",
        LABEL_BAILOUT_PLAN: "Bailout Plan",
        LABEL_BAILOUT_MODEL: "Bailout Model",
        LABEL_BAILOUT_GF_LO: "Bailout GF Lo",
        LABEL_BAILOUT_GF_HI: "Bailout GF Hi",
        LABEL_BAILOUT_RMV: "Bailout RMV",
        LABEL_EXTRA_BOTTOM_MIN: "Extra Bottom Min",
        LABEL_EXTRA_TIME_MIN: "Extra Time (min)",
        LABEL_BAILOUT_GFS: "Bailout GFS Hi",
        LABEL_BAILOUT_DIVE_NUM: "Bailout Dive #",
        LABEL_CAVE_TYPE_BAIL: "Cave Type Bail",
        LABEL_RETURN_PORTION: "Return Portion",
        CARD_MULTI_DIVE: "Surface Interval / Multi-dive",
        LABEL_2WEEK_OTU: "2-Week OTU",
        UNIT_CUMULATIVE: "cumulative",
        LABEL_TRAVEL_O2: "Travel Gas O2%",
        LABEL_TRAVEL_HE: "Travel Gas He%",
        BTN_RESET_CONFIG: "Reset Configuration",
        BTN_LOAD_DEBUG_INFO: "Load Debug Info",
        HOF_TITLE: "Donation Hall of Fame",
        HOF_BTN_DONATE: "How to make a Donation",
        HOF_BTN_CALL: "Make Call to Developers",
        HOF_FOUNDERS: "Founders Donation Section",
        HOF_GOLD: "Gold Donation Section",
        HOF_SILVER: "Silver Donation Section",
        HOF_BRONZE: "Bronze Donation Section",
        TOOL_BESTMIX: "Best Mix",
        TOOL_EADMOD: "EAD, MOD, END",
        TOOL_NITROX: "Mix Nitrox",
        TOOL_TRIMIX: "Mix Trimix",
        TOOL_TOPUP: "Mix Topup",
        TOOL_CAPACITY: "Mix Fill",
        TOOL_DENSITY: "Density",
        TOOL_MIXCONFIG: "Mix Config",
        LABEL_PPO2_LIMIT: "ppO2 Limit",
        LABEL_TRIMIX: "Trimix",
        LABEL_EAD_DEPTH: "EAD Depth",
        LABEL_O2: "O2",
        LABEL_HE: "He",
        LABEL_PPO2_FOR_MOD: "ppO2 for MOD",
        LABEL_SETPOINT_CCR: "Setpoint (CCR)",
        LABEL_MIX_PRESSURE_UNITS: "Pressure Units",
        LABEL_MIX_TEMP_UNITS: "Temperature Units",
        LABEL_MIX_TEMPERATURE: "Temperature",
        LABEL_BANKED_GAS: "Banked Gas",
        OPT_TEMP_C: "C",
        OPT_TEMP_F: "F",
        OPT_BANKED_AIR: "Air",
        OPT_BANKED_32: "32",
        RESULT_BEST_MIX: "Best Mix",
        RESULT_MOD: "MOD",
        RESULT_EAD: "EAD",
        RESULT_END: "END",
        RESULT_EADD: "EADD",
        LABEL_OLD_PRESSURE: "Old Pressure",
        LABEL_NEW_PRESSURE: "New Pressure",
        LABEL_OLD_O2: "Old O2",
        LABEL_NEW_O2: "New O2",
        LABEL_OLD_HE: "Old He",
        LABEL_NEW_HE: "New He",
        LABEL_ADD_FIRST: "Add First",
        OPT_ADD_HE_FIRST: "He",
        OPT_ADD_O2_FIRST: "O2",
        LABEL_START_PRESSURE: "Start Pressure",
        LABEL_START_O2: "Start O2",
        LABEL_START_HE: "Start He",
        LABEL_END_PRESSURE: "End Pressure",
        LABEL_END_O2: "End O2",
        LABEL_END_HE: "End He",
        LABEL_FILL_ORDER: "Fill Order",
        OPT_HE_FIRST: "He first",
        OPT_O2_FIRST: "O2 first",
        RESULT_ADD_O2: "Add O2",
        RESULT_ADD_AIR: "Add Air",
        RESULT_ADD_32: "Add 32",
        RESULT_ADD_HE: "Add He",
        RESULT_TEST_O2: "Test O2",
        LABEL_TOPUP_WITH_O2: "Top up with O2",
        LABEL_TOPUP_WITH_HE: "Top up with He",
        RESULT_TOPUP_RESULT: "Result",
        LABEL_CURRENT_PRESSURE: "Current Pressure",
        LABEL_CURRENT_O2: "Current O2",
        LABEL_CURRENT_HE: "Current He",
        LABEL_ADD_PRESSURE: "Add Pressure",
        LABEL_TOP_GAS_O2: "Top Gas O2",
        LABEL_TOP_GAS_HE: "Top Gas He",
        RESULT_FINAL_O2: "Final O2 %",
        RESULT_FINAL_HE: "Final He %",
        RESULT_FINAL_PRESSURE: "Final Pressure",
        LABEL_SUPPLY_TANK: "Supply Tank",
        LABEL_WATER_CAPACITY: "Water Capacity",
        LABEL_PRESSURE: "Pressure",
        LABEL_RECEIVING_TANK: "Receiving Tank",
        RESULT_EQ_PRESSURE: "Equalized Pressure",
        LABEL_SUPPLY_START_PRESSURE: "Supply Start Pressure",
        LABEL_SUPPLY_SIZE: "Supply Size",
        LABEL_RECEIVE_SIZE: "Receive Size",
        LABEL_RECEIVE_START_PRESSURE: "Receive Start Pressure",
        LABEL_RECEIVE_ADD_PRESSURE: "Receive Add Pressure",
        BTN_EQUALIZE: "Equalize",
        BTN_REPEAT: "Repeat",
        RESULT_SUPPLY_RESULT: "Supply Result",
        RESULT_RECEIVE_RESULT: "Receive Result",
        WARN_MIXFILL_LOW_SUPPLY: "Supply result is lower than receive result.",
        LABEL_DENSITY_MODE: "Mode",
        OPT_SP: "SP",
        LABEL_TEMP_MODE: "Temperature",
        OPT_0C: "0C",
        OPT_20C: "20C",
        WARN_DENSITY_HIGH: "Gas density exceeds 6.2 g/L - high risk of CO2 retention!",
        WARN_DENSITY_MEDIUM: "Gas density above 5.2 g/L - increased work of breathing.",
        RESULT_DIVE_HEADER: "Dive #{n} Plan Result",
        TABLE_ACTION: "Action",
        TABLE_DEPTH: "Depth",
        TABLE_STOP: "Stop",
        TABLE_RUN: "Run",
        TABLE_MIX: "Mix",
        TABLE_PPO2: "pO2",
        TABLE_EAD: "EAD",
        ACTION_DESC: "Des",
        ACTION_LVL: "Lvl",
        ACTION_ASC: "Asc",
        ACTION_STP: "Stp",
        ACTION_SFC: "Sfc",
        BTN_NEXT_DIVE: "NEXT DIVE",
        BTN_TEXT_REPORT: "Text Report",
        BTN_DEBUG_INFO: "DEBUG INFO TO DEVELOPER",
        MODAL_REPORT_TITLE: "Dive Plan Report",
        MODAL_SURFACE_INTERVAL: "Surface Interval",
        UNIT_DAYS: "days",
        UNIT_HOURS: "hours",
        UNIT_MINUTES: "min",
        LABEL_SI_TOTAL: "Total: {n} min",
        MSG_SI_DESCRIPTION: "Set the time between dives. Tissues will off-gas during this interval.",
        BTN_START_NEXT_DIVE: "Start Next Dive",
        AXIS_RUNTIME: "Runtime (min)",
        AXIS_PRESSURE: "Pressure (bar)",
        MSG_COPIED: "Dive plan copied to clipboard.",
        MSG_COPY_FAILED: "Failed to copy to clipboard.",
        MSG_COPIED_SHORT: "Copied!",
        MSG_TISSUES_RESET: "Surface tissues reset. Next dive will be planned as Dive #1.",
        ERR_NO_LEVELS: "Add at least one bottom level before calculating.",
        ERR_NO_RESULT: "No completed dive to continue from. Calculate a dive plan first.",
        ERR_CALC: "Calculation error: {error}",
        WARN_PPO2_HI_DETAIL: "ppO2 {val} > {threshold} at {depth}m ({gas})",
        UNIT_M: "m",
        UNIT_FT: "ft",
        UNIT_L: "L",
        UNIT_M_MIN: "m/min",
        UNIT_FT_MIN: "ft/min",
        UNIT_L_MIN: "L/min",
        UNIT_CUFT_MIN: "cu ft/min",
        UNIT_G_L: "g/L",
        UNIT_LITERS_WORD: "liters",
        ACTION_DES_SHORT: "Des",
        ACTION_LVL_SHORT: "Lvl",
        ACTION_STP_SHORT: "Stp",
        ACTION_SFC_SHORT: "Sfc",
        SUMMARY_ELEVATION_LABEL: "Elevation",
        SUMMARY_RUNTIME_LABEL: "Runtime",
        SUMMARY_DECO_LABEL: "Deco",
        SUMMARY_STOPS_LABEL: "Stops",
        SUMMARY_CNS_LABEL: "CNS",
        SUMMARY_OTU_LABEL: "OTU",
        SUMMARY_GAS_PREFIX: "Gas",
        SUMMARY_GAS_DENSITY: "Gas density",
        SUMMARY_DECO_ZONE: "Deco zone",
        SUMMARY_GF_LABEL: "GF",
        CHART_XAXIS_TIME: "Time ({u})",
        CHART_YAXIS_DEPTH: "Depth ({u})",
        CHART_TITLE_DEPTH: "Depth {d}{u}",
        CHART_SERIES_DEPTH: "Depth",
        CHART_SERIES_GAS: "Gas",
        CHART_TOOLTIP_TIME: "Time",
        CHART_TOOLTIP_DEPTH: "Depth",
        ABOUT_TITLE: "ApexDeco",
        ABOUT_SUBTITLE: "Dive Decompression Planner",
        ABOUT_MATH_TESTS: "Math verification: every tool and every decompression primitive is covered by an automated test with tolerance checks against reference values. You can run the full test suite in your browser:",
        ABOUT_TESTS_LINK: "open tests.html",
        ABOUT_ALGORITHMS: "Based on the Bühlmann ZH-L16C algorithm with Gradient Factors. Implements decompression planning for OC and CCR diving. Includes gas mixing tools.",
        ABOUT_COPYRIGHT: "Copyright © Alexey Vlasov. Licensed under the",
        ABOUT_LICENSE_LINK: "GNU Affero General Public License v3.0 (AGPLv3)",
        ABOUT_WARNING_TITLE: "WARNING!",
        ABOUT_WARNING_TEXT: "THERE IS ALWAYS A RISK OF DECOMPRESSION SICKNESS WHEN DIVING. USE THIS PLANNER AT YOUR OWN RISK. ALWAYS FOLLOW SAFE DIVING PRACTICES AND CONSULT WITH PROFESSIONAL DIVE INSTRUCTORS.",
        MSG_DEBUG_COPIED: "Debug Info copied to clipboard.",
        MSG_DEBUG_COPY_FAILED: "Failed to copy debug info to clipboard.",
        MSG_DEBUG_LOADED: "Debug info loaded from clipboard.",
        MSG_DEBUG_LOAD_FAILED: "Failed to load debug info from clipboard.",
        UNIT_MIN: "min",
        UNIT_BAR: "bar",
        UNIT_PSI: "psi",
        UNIT_CUFT: "cu.ft",
        UNIT_AIR_RATIO: "× Air",
        ABOUT_MATH_TESTS_FULL: "Math verification tests. The engine is validated against the original Android MultiDeco binary (libmultideco.so). Each gas-mixing tool (Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density) and every decompression primitive (ZH-L16C Schreiner loading, Gradient Factor ceiling, VPM-B boundary/critical volume, CCR setpoint, extended stops, OTU/CNS, fresh/salt water SLP behavior) is covered by an automated test with tolerance checks against Android-reference values. You can run the full test suite in your browser:",
        ABOUT_ALGORITHMS_FULL: "Based on the Bühlmann ZH-L16C algorithm with Gradient Factors. Implements decompression planning for OC diving. Includes gas mixing tools: Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density.",
        ABOUT_WARNING_TEXT_FULL: "THERE IS ALWAYS A RISK OF DECOMPRESSION SICKNESS (DCS) FOR ANY DIVE PROFILE EVEN IF YOU FOLLOW THE DIVE PLAN PRESCRIBED BY DIVE TABLES. NO PROCEDURE OR DIVE TABLE WILL PREVENT THE POSSIBILITY OF DCS OR OXYGEN TOXICITY! An individual's physiological make up can vary from day to day. You are strongly advised to remain well within the exposure limits provided by the planner to minimize the risk of DCS.",
        RESULT_GAS_USAGE: "Gas Usage",
        RESULT_TH_VOLUME: "Volume",
        RESULT_TH_24Lx2: "24L x2",
        RESULT_PP_TITLE: "Gas Partial Pressures",
        CHART_XAXIS_RUNTIME: "Runtime (min)",
        CHART_YAXIS_PRESSURE: "Pressure (bar)",
        CHART_COMP: "Comp {n}",
        RESULT_GRID_PLAN: "Grid Plan",
        TH_ACTION: "Action",
        TH_DEPTH: "Depth",
        TH_TIME: "Time",
        TH_RUNTIME: "RunTime",
        TH_O2: "O2",
        TH_HE: "He",
        TH_SETPOINT: "Setpoint",
        TH_PPO2: "pO2",
        TH_EAD: "EAD",
        TH_END: "END",
        TH_CNS: "CNS",
        TH_OTU: "OTU's",
        TH_SEG: "Seg",
        TH_GAS: "Gas",
        ACTION_DESCENT: "Descent",
        ACTION_LEVEL: "Level",
        ACTION_ASCENT: "Ascent",
        ACTION_STOP: "Stop",
        ACTION_SURFACE: "Surface",
        ACTION_STOP_SHORT: "Stop",
        ACTION_DESC_SHORT: "Desc",
        ACTION_ASC_SHORT: "Asc",
        ACTION_BOTTOM_SHORT: "Bottom",
        ACTION_SURF_SHORT: "Surf",
        RESULT_BAILOUT_PLAN: "Bailout Plan — {model}",
        RESULT_BAILOUT_GAS_REQ: "Bailout Gas Required",
        REPORT_TITLE: "ApexDeco - Dive Plan",
        REPORT_CIRCUIT: "Circuit",
        REPORT_MODEL: "Model",
        REPORT_UNITS: "Units",
        REPORT_UNITS_METRIC: "Metric",
        REPORT_UNITS_IMPERIAL: "Imperial",
        REPORT_WATER_SALT: "Salt water",
        REPORT_WATER_FRESH: "Fresh water",
        REPORT_BOTTOM_LEVELS: "Bottom Levels:",
        REPORT_DECO_MIXES: "Deco Mixes:",
        REPORT_PLAN: "Plan:",
        REPORT_TH_SEGMENT: "Segment",
        REPORT_TH_DEPTH: "Depth",
        REPORT_TH_TIME: "Time",
        REPORT_TH_RUN: "Run",
        REPORT_TH_GAS: "Gas",
        REPORT_TOTAL_RUNTIME: "Total Runtime",
        REPORT_OTU: "OTU",
        REPORT_CNS: "CNS",
        WARN_INVALID_MIX: "Invalid mix - check values.",
        UNIT_BAR_OC: "bar (0 = OC)",
        UNIT_MIN_OFF: "min (0 = off)",
        GAS_TRIMIX: "Trimix",
        GAS_NITROX: "Nitrox",
        CONFIRM_RESET: "Reset all settings to defaults?"
    },
    ru: {
        APP_TITLE: "ApexDeco",
        CHART_NO_HE: "В этом погружении нет гелия — рассыщать нечего.",
        CHART_SUPERSAT_TITLE: "Газонапряжение в тканевых компартментах",
        CHART_MODE_SUPERSAT: "Перенасыщ.",
        CHART_MODE_N2: "N2 рассыщ.",
        CHART_MODE_HE: "He рассыщ.",
        CHART_MODE_SURF: "К поверхности",
        CHART_TITLE_SUPERSAT: "Перенасыщение тканей: сумм. Pткани - Pamb",
        CHART_TITLE_N2: "Градиент рассыщения N2: pN2 - pAlv*fN2",
        CHART_TITLE_HE: "Градиент рассыщения He: pHe",
        CHART_TITLE_SURF: "Рассыщение к поверхности: Pткани - Psurf",
        CHART_X_RUNTIME: "Время от старта (мин)",
        CHART_COMP_MAX: "Макс",
        CHART_COMP_ALL: "Все",
        BTN_NAV_PLAN: "План",
        BTN_NAV_HELP: "Помощь",
        BTN_NAV_SETTINGS: "Опции",
        BTN_NAV_TOOLS: "Инструменты",
        CARD_BOTTOM_MIX: "Донный газ и переход",
        CARD_DECO_MIXES: "Декогазы",
        BTN_ADD_LEVEL: "+ Добавить уровень",
        BTN_ADD_DECO: "+ Добавить деко",
        BTN_DELETE: "Удалить",
        BTN_CALCULATE: "Рассчитать",
        BTN_RESET_TISSUES: "Сбросить ткани на поверхности",
        MSG_NO_BOTTOM_LEVELS: "Нет донных уровней. Нажмите + Добавить уровень.",
        MSG_NO_DECO_MIXES: "Нет декогазов. Нажмите + Добавить деко.",
        MODAL_TITLE_ADD_LEVEL: "Добавить донный газ и переход",
        MODAL_TITLE_EDIT_LEVEL: "Изменить донный газ и переход",
        MODAL_TITLE_ADD_DECO: "Добавить декогаз",
        MODAL_TITLE_EDIT_DECO: "Изменить декогаз",
        LABEL_DEPTH: "Глубина",
        LABEL_TIME_MIN: "Время (мин)",
        LABEL_O2_PERCENT: "O2 %",
        LABEL_HE_PERCENT: "He %",
        LABEL_DEPTH_CHANGE_OVERRIDE: "Переопределение глубины смены",
        LABEL_SETPOINT: "Сетпоинт",
        LABEL_OC_OR_SCR: "Сегмент OC или SCC:",
        BTN_SAVE: "Сохранить",
        BTN_CANCEL: "Отмена",
        BTN_OK: "OK",
        BTN_COPY: "Копировать",
        BTN_CLOSE: "Закрыть",
        ERR_O2_HE_EXCEED: "O2 + He не могут превышать 100%",
        ERR_INVALID_DECO_SWITCH_DEPTH: "Введите корректную глубину смены декогаза.",
        CARD_APPEARANCE: "Оформление",
        LABEL_LANGUAGE: "Язык",
        LABEL_INTERFACE_STYLE: "Стиль интерфейса",
        OPT_LIGHT_THEME: "Светлая тема",
        OPT_DARK_THEME: "Тёмная тема",
        CARD_MODEL_SETTINGS: "Настройки модели",
        LABEL_CIRCUIT: "Контур",
        OPT_OC: "OC",
        OPT_CCR: "CCR",
        LABEL_DECO_MODEL: "Модель декомпрессии",
        LABEL_CONSERVATISM: "Консерватизм",
        LABEL_GF_LO: "GF Lo",
        LABEL_GF_HI: "GF Hi",
        LABEL_O2_NARCOTIC: "O2 наркотичен",
        OPT_YES: "Да",
        OPT_NO: "Нет",
        CARD_UNIT_SETTINGS: "Единицы измерения",
        LABEL_DEPTH_UNITS: "Единицы глубины",
        OPT_METER: "Метры",
        OPT_FEET: "Футы",
        LABEL_WATER_TYPE: "Тип воды",
        OPT_SALT: "Солёная",
        OPT_FRESH: "Пресная",
        LABEL_ALTITUDE: "Высота (м)",
        LABEL_ACCLIMATIZED: "Акклиматизация (м)",
        LABEL_GAS_VOLUME: "Объём газа",
        OPT_LITER: "Литр",
        OPT_CUFT: "CuFt",
        LABEL_PRESSURE_UNITS: "Единицы давления",
        LABEL_GAUGE_TYPE: "Тип манометра",
        OPT_SIMPLE: "Простой",
        OPT_DIGITAL: "Цифровой",
        LABEL_TEMPERATURE: "Температура",
        CARD_RATES: "Скорости спуска / всплытия",
        LABEL_DESCENT_RATE: "Скорость спуска",
        LABEL_ASCENT_RATE: "Скорость всплытия",
        LABEL_DECO_ASCENT_RATE: "Скорость всплытия на деко",
        LABEL_SURFACE_ASCENT_RATE: "Скорость всплытия к поверхности",
        CARD_DECO_STOPS: "Настройки декоостановок",
        LABEL_STEP_SIZE: "Шаг остановок",
        LABEL_LAST_STOP_OC: "Последняя остановка (OC)",
        LABEL_LAST_STOP_CCR: "Последняя остановка (CCR)",
        LABEL_MIN_STOP_TIME: "Мин. время остановки",
        OPT_STOP_1MIN: "1 мин",
        OPT_STOP_30S: "30 сек",
        OPT_STOP_10S: "10 сек",
        OPT_STOP_1S: "1 сек",
        LABEL_PPO2_SWAP: "ppO2 для смены деко",
        LABEL_PPO2_MID_MIX: "ppO2 смеси 28-45%",
        LABEL_PPO2_HIGH_MIX: "ppO2 смеси 45-99%",
        LABEL_PPO2_BOTTOM_MAX: "ppO2 макс. на дне",
        LABEL_O2_MAX_DEPTH: "Макс. глубина O2 100%",
        LABEL_FIRST_STOP_30S: "Первая остановка 30 сек",
        LABEL_FIRST_STOP_DBL: "Первая остановка двойной шаг",
        OPT_OFF: "Выкл",
        OPT_ON: "Вкл",
        CARD_CCR_SETTINGS: "Настройки CCR",
        LABEL_DEFAULT_SETPOINT: "Сетпоинт по умолчанию",
        LABEL_SP_UNITS: "Единицы SP",
        CARD_RMV: "RMV / Планирование газа",
        LABEL_BOTTOM_RMV: "Донный RMV",
        LABEL_DECO_RMV: "Деко RMV",
        LABEL_CCR_DIL_RMV: "Метаболизм дил. CCR",
        CARD_EXTENDED_STOPS: "Удлинённые остановки",
        LABEL_EXTENDED_STOPS: "Удлинённые остановки",
        LABEL_ADD_TIME_STOP: "Добавить время к остановке",
        LABEL_ALL_MIX_CHANGES: "Все смены газа",
        LABEL_O2_WINDOW: "Эффект O2-окна",
        MSG_EXT_STOPS_DESC: "Включать удлинённые остановки при смене декогазов",
        LABEL_EXT_SHALLOW: "7..30 м",
        LABEL_EXT_DEEP: "30 + м",
        CARD_WARNINGS: "Пороги предупреждений",
        LABEL_WARN_PPO2_HI: "ppO2 макс.",
        LABEL_WARN_PPO2_LO: "ppO2 мин.",
        LABEL_WARN_CNS: "CNS % выше",
        LABEL_WARN_OTU: "OTU выше",
        LABEL_WARN_IBCD_N2: "IBCD N2",
        LABEL_WARN_IBCD_HE: "IBCD He",
        LABEL_WARN_CCR_DIL: "Проверка дилюента CCR",
        MSG_CCR_DIL_CHECK: "Проверка ppO2 дилюента относительно сетпоинта",
        CARD_BAILOUT: "Настройки bailout",
        LABEL_BAILOUT_PLAN: "Bailout-план",
        LABEL_BAILOUT_MODEL: "Модель bailout",
        LABEL_BAILOUT_GF_LO: "Bailout GF Lo",
        LABEL_BAILOUT_GF_HI: "Bailout GF Hi",
        LABEL_BAILOUT_RMV: "Bailout RMV",
        LABEL_EXTRA_BOTTOM_MIN: "Доп. донное время",
        LABEL_EXTRA_TIME_MIN: "Доп. время (мин)",
        LABEL_BAILOUT_GFS: "Bailout GFS Hi",
        LABEL_BAILOUT_DIVE_NUM: "Bailout погружение №",
        LABEL_CAVE_TYPE_BAIL: "Тип bailout в пещере",
        LABEL_RETURN_PORTION: "Доля возврата",
        CARD_MULTI_DIVE: "Поверхностный интервал / Серия погружений",
        LABEL_2WEEK_OTU: "OTU за 2 недели",
        UNIT_CUMULATIVE: "накопительно",
        LABEL_TRAVEL_O2: "O2% газа перехода",
        LABEL_TRAVEL_HE: "He% газа перехода",
        BTN_RESET_CONFIG: "Сбросить конфигурацию",
        BTN_LOAD_DEBUG_INFO: "Загрузить отладочную информацию",
        HOF_TITLE: "Зал славы",
        HOF_BTN_DONATE: "Как сделать пожертвование",
        HOF_BTN_CALL: "Сделать звонок разработчикам",
        HOF_FOUNDERS: "Секция основателей",
        HOF_GOLD: "Золотая секция",
        HOF_SILVER: "Серебряная секция",
        HOF_BRONZE: "Бронзовая секция",
        TOOL_BESTMIX: "Оптимальная смесь",
        TOOL_EADMOD: "EAD, MOD, END",
        TOOL_NITROX: "Смешивание Nitrox",
        TOOL_TRIMIX: "Смешивание Trimix",
        TOOL_TOPUP: "Добивка смеси",
        TOOL_CAPACITY: "Заполнение смеси",
        TOOL_DENSITY: "Плотность",
        TOOL_MIXCONFIG: "Конфиг миксера",
        LABEL_PPO2_LIMIT: "Лимит ppO2",
        LABEL_TRIMIX: "Тримикс",
        LABEL_EAD_DEPTH: "Глубина EAD",
        LABEL_O2: "O2",
        LABEL_HE: "He",
        LABEL_PPO2_FOR_MOD: "ppO2 для MOD",
        LABEL_SETPOINT_CCR: "Сетпоинт (CCR)",
        LABEL_MIX_PRESSURE_UNITS: "Единицы давления",
        LABEL_MIX_TEMP_UNITS: "Единицы температуры",
        LABEL_MIX_TEMPERATURE: "Температура",
        LABEL_BANKED_GAS: "Банк газа",
        OPT_TEMP_C: "C",
        OPT_TEMP_F: "F",
        OPT_BANKED_AIR: "Воздух",
        OPT_BANKED_32: "32",
        RESULT_BEST_MIX: "Оптимальная смесь",
        RESULT_MOD: "MOD",
        RESULT_EAD: "EAD",
        RESULT_END: "END",
        RESULT_EADD: "EADD",
        LABEL_OLD_PRESSURE: "Старое давление",
        LABEL_NEW_PRESSURE: "Новое давление",
        LABEL_OLD_O2: "Старый O2",
        LABEL_NEW_O2: "Новый O2",
        LABEL_OLD_HE: "Старый He",
        LABEL_NEW_HE: "Новый He",
        LABEL_ADD_FIRST: "Добавлять первым",
        OPT_ADD_HE_FIRST: "He",
        OPT_ADD_O2_FIRST: "O2",
        LABEL_START_PRESSURE: "Начальное давление",
        LABEL_START_O2: "Начальный O2",
        LABEL_START_HE: "Начальный He",
        LABEL_END_PRESSURE: "Конечное давление",
        LABEL_END_O2: "Конечный O2",
        LABEL_END_HE: "Конечный He",
        LABEL_FILL_ORDER: "Порядок заправки",
        OPT_HE_FIRST: "Сначала He",
        OPT_O2_FIRST: "Сначала O2",
        RESULT_ADD_O2: "Добавить O2",
        RESULT_ADD_AIR: "Добавить воздух",
        RESULT_ADD_32: "Добавить 32",
        RESULT_ADD_HE: "Добавить He",
        RESULT_TEST_O2: "Замер O2",
        LABEL_TOPUP_WITH_O2: "Добить O2",
        LABEL_TOPUP_WITH_HE: "Добить He",
        RESULT_TOPUP_RESULT: "Результат",
        LABEL_CURRENT_PRESSURE: "Текущее давление",
        LABEL_CURRENT_O2: "Текущий O2",
        LABEL_CURRENT_HE: "Текущий He",
        LABEL_ADD_PRESSURE: "Добавить давление",
        LABEL_TOP_GAS_O2: "O2 дозаправочного газа",
        LABEL_TOP_GAS_HE: "He дозаправочного газа",
        RESULT_FINAL_O2: "Итоговый O2 %",
        RESULT_FINAL_HE: "Итоговый He %",
        RESULT_FINAL_PRESSURE: "Итоговое давление",
        LABEL_SUPPLY_TANK: "Баллон-источник",
        LABEL_WATER_CAPACITY: "Водяной объём",
        LABEL_PRESSURE: "Давление",
        LABEL_RECEIVING_TANK: "Баллон-приёмник",
        RESULT_EQ_PRESSURE: "Давление после выравнивания",
        LABEL_SUPPLY_START_PRESSURE: "Стартовое давление источника",
        LABEL_SUPPLY_SIZE: "Объём источника",
        LABEL_RECEIVE_SIZE: "Объём приёмника",
        LABEL_RECEIVE_START_PRESSURE: "Стартовое давление приёмника",
        LABEL_RECEIVE_ADD_PRESSURE: "Добавляемое давление приёмнику",
        BTN_EQUALIZE: "Уравнять",
        BTN_REPEAT: "Повтор",
        RESULT_SUPPLY_RESULT: "Результат источника",
        RESULT_RECEIVE_RESULT: "Результат приёмника",
        WARN_MIXFILL_LOW_SUPPLY: "Давление в источнике ниже давления в приёмнике.",
        LABEL_DENSITY_MODE: "Режим",
        OPT_SP: "SP",
        LABEL_TEMP_MODE: "Температура",
        OPT_0C: "0C",
        OPT_20C: "20C",
        WARN_DENSITY_HIGH: "Плотность газа превышает 6.2 g/L — высокий риск задержки CO2!",
        WARN_DENSITY_MEDIUM: "Плотность газа выше 5.2 g/L — повышенная работа дыхания.",
        RESULT_DIVE_HEADER: "План погружения №{n}",
        TABLE_ACTION: "Шаг",
        TABLE_DEPTH: "Глубина",
        TABLE_STOP: "Стоп",
        TABLE_RUN: "Уход",
        TABLE_MIX: "Смесь",
        TABLE_PPO2: "pO2",
        TABLE_EAD: "EAD",
        ACTION_DESC: "Спу",
        ACTION_LVL: "Дно",
        ACTION_ASC: "Всп",
        ACTION_STP: "Ост",
        ACTION_SFC: "Пов",
        BTN_NEXT_DIVE: "СЛЕДУЮЩЕЕ ПОГРУЖЕНИЕ",
        BTN_TEXT_REPORT: "Отчёт",
        BTN_DEBUG_INFO: "ОТЧЕТ РАЗРАБОТЧИКА",
        MODAL_REPORT_TITLE: "Отчёт по плану погружения",
        MODAL_SURFACE_INTERVAL: "Поверхностный интервал",
        UNIT_DAYS: "дн",
        UNIT_HOURS: "ч",
        UNIT_MINUTES: "мин",
        LABEL_SI_TOTAL: "Всего: {n} мин",
        MSG_SI_DESCRIPTION: "Задайте время между погружениями. За этот интервал ткани выводят инертный газ.",
        BTN_START_NEXT_DIVE: "Начать следующее погружение",
        AXIS_RUNTIME: "Runtime (мин)",
        AXIS_PRESSURE: "Давление (bar)",
        MSG_COPIED: "План погружения скопирован в буфер обмена.",
        MSG_COPY_FAILED: "Не удалось скопировать в буфер обмена.",
        MSG_COPIED_SHORT: "Скопировано!",
        MSG_TISSUES_RESET: "Ткани на поверхности сброшены. Следующее погружение будет рассчитано как №1.",
        ERR_NO_LEVELS: "Добавьте хотя бы один донный уровень перед расчётом.",
        ERR_NO_RESULT: "Нет завершённого погружения для продолжения. Сначала рассчитайте план.",
        ERR_CALC: "Ошибка расчёта: {error}",
        WARN_PPO2_HI_DETAIL: "ppO2 {val} > {threshold} на {depth}м ({gas})",
        UNIT_M: "м",
        UNIT_FT: "футы",
        UNIT_L: "л",
        UNIT_M_MIN: "м/мин",
        UNIT_FT_MIN: "фут/мин",
        UNIT_L_MIN: "л/мин",
        UNIT_CUFT_MIN: "куб. фут/мин",
        UNIT_G_L: "г/л",
        UNIT_LITERS_WORD: "литров",
        ACTION_DES_SHORT: "Спуск",
        ACTION_LVL_SHORT: "Уров",
        ACTION_STP_SHORT: "Ост",
        ACTION_SFC_SHORT: "Пов",
        SUMMARY_ELEVATION_LABEL: "Высота",
        SUMMARY_RUNTIME_LABEL: "Всего",
        SUMMARY_DECO_LABEL: "Деко",
        SUMMARY_STOPS_LABEL: "Остановки",
        SUMMARY_CNS_LABEL: "CNS",
        SUMMARY_OTU_LABEL: "OTU",
        SUMMARY_GAS_PREFIX: "Газ",
        SUMMARY_GAS_DENSITY: "Плотность газа",
        SUMMARY_DECO_ZONE: "Декозона",
        SUMMARY_GF_LABEL: "GF",
        CHART_XAXIS_TIME: "Время ({u})",
        CHART_YAXIS_DEPTH: "Глубина ({u})",
        CHART_TITLE_DEPTH: "Глубина {d}{u}",
        CHART_SERIES_DEPTH: "Глубина",
        CHART_SERIES_GAS: "Газ",
        CHART_TOOLTIP_TIME: "Время",
        CHART_TOOLTIP_DEPTH: "Глубина",
        ABOUT_TITLE: "ApexDeco",
        ABOUT_SUBTITLE: "Планировщик декомпрессионных погружений",
        ABOUT_MATH_TESTS: "Проверка математики: каждый инструмент и каждый декомпрессионный примитив покрыт автоматическим тестом со сверкой допусков относительно эталонных значений. Полный набор тестов можно запустить в браузере:",
        ABOUT_TESTS_LINK: "открыть tests.html",
        ABOUT_ALGORITHMS: "Основан на алгоритме Бюльмана ZH-L16C с градиент-факторами. Реализует планирование декомпрессии для погружений на открытом и замкнутом цикле (OC и CCR). Включает инструменты для смешивания газов.",
        ABOUT_COPYRIGHT: "Copyright © Алексей Власов. Распространяется по лицензии",
        ABOUT_LICENSE_LINK: "GNU Affero General Public License v3.0 (AGPLv3)",
        ABOUT_WARNING_TITLE: "ВНИМАНИЕ!",
        ABOUT_WARNING_TEXT: "ПРИ ПОГРУЖЕНИЯХ ВСЕГДА СУЩЕСТВУЕТ РИСК ДЕКОМПРЕССИОННОЙ БОЛЕЗНИ. ИСПОЛЬЗУЙТЕ ДАННЫЙ ПЛАНИРОВЩИК НА СВОЙ СТРАХ И РИСК. ВСЕГДА СОБЛЮДАЙТЕ БЕЗОПАСНУЮ ПРАКТИКУ ДАЙВИНГА И КОНСУЛЬТИРУЙТЕСЬ С ПРОФЕССИОНАЛЬНЫМИ ИНСТРУКТОРАМИ.",
        MSG_DEBUG_COPIED: "Отладочная информация скопирована в буфер обмена.",
        MSG_DEBUG_COPY_FAILED: "Не удалось скопировать отладочную информацию.",
        MSG_DEBUG_LOADED: "Отладочная информация загружена из буфера обмена.",
        MSG_DEBUG_LOAD_FAILED: "Не удалось загрузить отладочную информацию из буфера обмена.",
        UNIT_MIN: "мин",
        UNIT_BAR: "бар",
        UNIT_PSI: "psi",
        UNIT_CUFT: "куб.фут",
        UNIT_AIR_RATIO: "× воздуха",
        ABOUT_MATH_TESTS_FULL: "Тесты математической проверки. Движок проверен относительно оригинального Android-бинарника MultiDeco (libmultideco.so). Каждый инструмент смешивания газов (Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density) и каждый декомпрессионный примитив (нагрузка ZH-L16C по Шрайнеру, потолок по градиент-факторам, граница/критический объём VPM-B, сетпоинт CCR, расширенные остановки, OTU/CNS, поведение SLP в пресной/солёной воде) покрыт автоматическим тестом со сверкой допусков по эталонам Android. Полный набор тестов можно запустить в браузере:",
        ABOUT_ALGORITHMS_FULL: "Основан на алгоритме Бюльмана ZH-L16C с градиент-факторами. Реализует планирование декомпрессии для погружений на открытом цикле (OC). Включает инструменты смешивания газов: Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density.",
        ABOUT_WARNING_TEXT_FULL: "ПРИ ЛЮБОМ ПРОФИЛЕ ПОГРУЖЕНИЯ ВСЕГДА СУЩЕСТВУЕТ РИСК ДЕКОМПРЕССИОННОЙ БОЛЕЗНИ (ДКБ), ДАЖЕ ЕСЛИ ВЫ СЛЕДУЕТЕ ПЛАНУ ПО ДЕКОМПРЕССИОННЫМ ТАБЛИЦАМ. НИ ОДНА ПРОЦЕДУРА ИЛИ ТАБЛИЦА НЕ ИСКЛЮЧАЕТ ВЕРОЯТНОСТЬ ДКБ ИЛИ КИСЛОРОДНОГО ОТРАВЛЕНИЯ! Физиологическое состояние человека может меняться день ото дня. Настоятельно рекомендуется оставаться значительно ниже предельных значений экспозиции, рассчитанных планировщиком, чтобы минимизировать риск ДКБ.",
        RESULT_GAS_USAGE: "Расход газа",
        RESULT_TH_VOLUME: "Объём",
        RESULT_TH_24Lx2: "24L x2",
        RESULT_PP_TITLE: "Парциальные давления газов",
        CHART_XAXIS_RUNTIME: "Время погружения (мин)",
        CHART_YAXIS_PRESSURE: "Давление (бар)",
        CHART_COMP: "Ткань {n}",
        RESULT_GRID_PLAN: "Детальный план",
        TH_ACTION: "Действие",
        TH_DEPTH: "Глубина",
        TH_TIME: "Время",
        TH_RUNTIME: "RunTime",
        TH_O2: "O2",
        TH_HE: "He",
        TH_SETPOINT: "Сетпоинт",
        TH_PPO2: "pO2",
        TH_EAD: "EAD",
        TH_END: "END",
        TH_CNS: "CNS",
        TH_OTU: "OTU",
        TH_SEG: "Сегм",
        TH_GAS: "Газ",
        ACTION_DESCENT: "Спуск",
        ACTION_LEVEL: "Уровень",
        ACTION_ASCENT: "Подъём",
        ACTION_STOP: "Остановка",
        ACTION_SURFACE: "Поверхность",
        ACTION_STOP_SHORT: "Ост",
        ACTION_DESC_SHORT: "Спуск",
        ACTION_ASC_SHORT: "Подъём",
        ACTION_BOTTOM_SHORT: "Дно",
        ACTION_SURF_SHORT: "Пов",
        RESULT_BAILOUT_PLAN: "План бэйлаута — {model}",
        RESULT_BAILOUT_GAS_REQ: "Требуется газа для бэйлаута",
        REPORT_TITLE: "ApexDeco - План погружения",
        REPORT_CIRCUIT: "Контур",
        REPORT_MODEL: "Модель",
        REPORT_UNITS: "Единицы",
        REPORT_UNITS_METRIC: "метрич.",
        REPORT_UNITS_IMPERIAL: "имперск.",
        REPORT_WATER_SALT: "солёная вода",
        REPORT_WATER_FRESH: "пресная вода",
        REPORT_BOTTOM_LEVELS: "Донные уровни:",
        REPORT_DECO_MIXES: "Декосмеси:",
        REPORT_PLAN: "План:",
        REPORT_TH_SEGMENT: "Сегмент",
        REPORT_TH_DEPTH: "Глубина",
        REPORT_TH_TIME: "Время",
        REPORT_TH_RUN: "Ход",
        REPORT_TH_GAS: "Газ",
        REPORT_TOTAL_RUNTIME: "Общее время",
        REPORT_OTU: "OTU",
        REPORT_CNS: "CNS",
        WARN_INVALID_MIX: "Некорректная смесь — проверьте значения.",
        GAS_TRIMIX: "Тримикс",
        GAS_NITROX: "Найтрокс",
        CONFIRM_RESET: "Сбросить все настройки к значениям по умолчанию?",
        UNIT_BAR_OC: "бар (0 = OC)",
        UNIT_MIN_OFF: "мин (0 = выкл.)"
    },
    es: {
        APP_TITLE: "ApexDeco",
        CHART_NO_HE: "No hay helio en esta inmersión — nada que desgasificar.",
        CHART_SUPERSAT_TITLE: "Tensión de gas en compartimentos tisulares",
        CHART_MODE_SUPERSAT: "Sobresat.",
        CHART_MODE_N2: "Desgas. N2",
        CHART_MODE_HE: "Desgas. He",
        CHART_MODE_SURF: "Hacia superficie",
        CHART_TITLE_SUPERSAT: "Sobresaturación tisular: Ptis total - Pamb",
        CHART_TITLE_N2: "Gradiente de desgas. N2: pN2 - pAlv*fN2",
        CHART_TITLE_HE: "Gradiente de desgas. He: pHe",
        CHART_TITLE_SURF: "Desgas. a superficie: Ptis - Psurf",
        CHART_X_RUNTIME: "Runtime (min)",
        CHART_COMP_MAX: "Máx",
        CHART_COMP_ALL: "Todos",
        BTN_NAV_PLAN: "Plan",
        BTN_NAV_HELP: "Ayuda",
        BTN_NAV_SETTINGS: "Ajustes",
        BTN_NAV_TOOLS: "Herram.",
        CARD_BOTTOM_MIX: "Mezcla de fondo y tránsito",
        CARD_DECO_MIXES: "Mezclas de deco",
        BTN_ADD_LEVEL: "+ Añadir nivel",
        BTN_ADD_DECO: "+ Añadir deco",
        BTN_DELETE: "Eliminar",
        BTN_CALCULATE: "Calcular",
        BTN_RESET_TISSUES: "Reiniciar tejidos en superficie",
        MSG_NO_BOTTOM_LEVELS: "Sin niveles de fondo. Pulse + Añadir nivel.",
        MSG_NO_DECO_MIXES: "Sin mezclas de deco. Pulse + Añadir deco.",
        MODAL_TITLE_ADD_LEVEL: "Añadir mezcla de fondo y tránsito",
        MODAL_TITLE_EDIT_LEVEL: "Editar mezcla de fondo y tránsito",
        MODAL_TITLE_ADD_DECO: "Añadir mezcla de deco",
        MODAL_TITLE_EDIT_DECO: "Editar mezcla de deco",
        LABEL_DEPTH: "Profundidad",
        LABEL_TIME_MIN: "Tiempo (min)",
        LABEL_O2_PERCENT: "O2 %",
        LABEL_HE_PERCENT: "He %",
        LABEL_DEPTH_CHANGE_OVERRIDE: "Anular profundidad de cambio",
        LABEL_SETPOINT: "Setpoint",
        LABEL_OC_OR_SCR: "Paso OC o SCR:",
        BTN_SAVE: "Guardar",
        BTN_CANCEL: "Cancelar",
        BTN_OK: "OK",
        BTN_COPY: "Copiar",
        BTN_CLOSE: "Cerrar",
        ERR_O2_HE_EXCEED: "O2 + He no puede superar el 100%",
        ERR_INVALID_DECO_SWITCH_DEPTH: "Introduzca una profundidad de cambio de deco válida.",
        CARD_APPEARANCE: "Apariencia",
        LABEL_LANGUAGE: "Idioma",
        LABEL_INTERFACE_STYLE: "Estilo de interfaz",
        OPT_LIGHT_THEME: "Tema claro",
        OPT_DARK_THEME: "Tema oscuro",
        CARD_MODEL_SETTINGS: "Ajustes del modelo",
        LABEL_CIRCUIT: "Circuito",
        OPT_OC: "OC",
        OPT_CCR: "CCR",
        LABEL_DECO_MODEL: "Modelo de deco",
        LABEL_CONSERVATISM: "Conservadurismo",
        LABEL_GF_LO: "GF Lo",
        LABEL_GF_HI: "GF Hi",
        LABEL_O2_NARCOTIC: "O2 narcótico",
        OPT_YES: "Sí",
        OPT_NO: "No",
        CARD_UNIT_SETTINGS: "Unidades",
        LABEL_DEPTH_UNITS: "Unidades de profundidad",
        OPT_METER: "Metros",
        OPT_FEET: "Pies",
        LABEL_WATER_TYPE: "Tipo de agua",
        OPT_SALT: "Salada",
        OPT_FRESH: "Dulce",
        LABEL_ALTITUDE: "Altitud (m)",
        LABEL_ACCLIMATIZED: "Aclimatado (m)",
        LABEL_GAS_VOLUME: "Volumen de gas",
        OPT_LITER: "Litro",
        OPT_CUFT: "CuFt",
        LABEL_PRESSURE_UNITS: "Unidades de presión",
        LABEL_GAUGE_TYPE: "Tipo de manómetro",
        OPT_SIMPLE: "Simple",
        OPT_DIGITAL: "Digital",
        LABEL_TEMPERATURE: "Temperatura",
        CARD_RATES: "Velocidades de descenso / ascenso",
        LABEL_DESCENT_RATE: "Velocidad de descenso",
        LABEL_ASCENT_RATE: "Velocidad de ascenso",
        LABEL_DECO_ASCENT_RATE: "Velocidad de ascenso en deco",
        LABEL_SURFACE_ASCENT_RATE: "Velocidad de ascenso a superficie",
        CARD_DECO_STOPS: "Ajustes de paradas de deco",
        LABEL_STEP_SIZE: "Paso entre paradas",
        LABEL_LAST_STOP_OC: "Última parada (OC)",
        LABEL_LAST_STOP_CCR: "Última parada (CCR)",
        LABEL_MIN_STOP_TIME: "Tiempo mín. de parada",
        OPT_STOP_1MIN: "1 min",
        OPT_STOP_30S: "30 seg",
        OPT_STOP_10S: "10 seg",
        OPT_STOP_1S: "1 seg",
        LABEL_PPO2_SWAP: "ppO2 cambio de deco",
        LABEL_PPO2_MID_MIX: "ppO2 mezcla 28-45%",
        LABEL_PPO2_HIGH_MIX: "ppO2 mezcla 45-99%",
        LABEL_PPO2_BOTTOM_MAX: "ppO2 máx. en fondo",
        LABEL_O2_MAX_DEPTH: "Prof. máx. O2 100%",
        LABEL_FIRST_STOP_30S: "Primera parada 30 seg",
        LABEL_FIRST_STOP_DBL: "Primera parada paso doble",
        OPT_OFF: "Off",
        OPT_ON: "On",
        CARD_CCR_SETTINGS: "Ajustes CCR",
        LABEL_DEFAULT_SETPOINT: "Setpoint por defecto",
        LABEL_SP_UNITS: "Unidades SP",
        CARD_RMV: "RMV / Planificación de gas",
        LABEL_BOTTOM_RMV: "RMV de fondo",
        LABEL_DECO_RMV: "RMV de deco",
        LABEL_CCR_DIL_RMV: "Metabolismo dil. CCR",
        CARD_EXTENDED_STOPS: "Paradas extendidas",
        LABEL_EXTENDED_STOPS: "Paradas extendidas",
        LABEL_ADD_TIME_STOP: "Añadir tiempo a la parada",
        LABEL_ALL_MIX_CHANGES: "Todos los cambios de mezcla",
        LABEL_O2_WINDOW: "Efecto ventana de O2",
        MSG_EXT_STOPS_DESC: "Incluir paradas extendidas al cambiar de mezcla de deco",
        LABEL_EXT_SHALLOW: "7..30 m",
        LABEL_EXT_DEEP: "30 + m",
        CARD_WARNINGS: "Umbrales de aviso",
        LABEL_WARN_PPO2_HI: "ppO2 alto",
        LABEL_WARN_PPO2_LO: "ppO2 bajo",
        LABEL_WARN_CNS: "CNS % por encima",
        LABEL_WARN_OTU: "OTU por encima",
        LABEL_WARN_IBCD_N2: "IBCD N2",
        LABEL_WARN_IBCD_HE: "IBCD He",
        LABEL_WARN_CCR_DIL: "Comprobación de diluyente CCR",
        MSG_CCR_DIL_CHECK: "Comprobar ppO2 del diluyente frente al setpoint",
        CARD_BAILOUT: "Ajustes de bailout",
        LABEL_BAILOUT_PLAN: "Plan de bailout",
        LABEL_BAILOUT_MODEL: "Modelo de bailout",
        LABEL_BAILOUT_GF_LO: "Bailout GF Lo",
        LABEL_BAILOUT_GF_HI: "Bailout GF Hi",
        LABEL_BAILOUT_RMV: "RMV de bailout",
        LABEL_EXTRA_BOTTOM_MIN: "Fondo extra mín.",
        LABEL_EXTRA_TIME_MIN: "Tiempo extra (min)",
        LABEL_BAILOUT_GFS: "Bailout GFS Hi",
        LABEL_BAILOUT_DIVE_NUM: "Inmersión de bailout #",
        LABEL_CAVE_TYPE_BAIL: "Tipo de bailout en cueva",
        LABEL_RETURN_PORTION: "Porción de regreso",
        CARD_MULTI_DIVE: "Intervalo en superficie / Multi-inmersión",
        LABEL_2WEEK_OTU: "OTU de 2 semanas",
        UNIT_CUMULATIVE: "acumulado",
        LABEL_TRAVEL_O2: "O2% gas de tránsito",
        LABEL_TRAVEL_HE: "He% gas de tránsito",
        BTN_RESET_CONFIG: "Restablecer configuración",
        BTN_LOAD_DEBUG_INFO: "Cargar info de depuración",
        HOF_TITLE: "Templo de la Fama de la Donación",
        HOF_BTN_DONATE: "Cómo hacer una Donación",
        HOF_BTN_CALL: "Hacer una Llamada al Desarrollador",
        HOF_FOUNDERS: "Sección de Fundadores",
        HOF_GOLD: "Sección de Oro",
        HOF_SILVER: "Sección de Plata",
        HOF_BRONZE: "Sección de Bronce",
        TOOL_BESTMIX: "Mejor mezcla",
        TOOL_EADMOD: "EAD, MOD, END",
        TOOL_NITROX: "Mezclar Nitrox",
        TOOL_TRIMIX: "Mezclar Trimix",
        TOOL_TOPUP: "Relleno de mezcla",
        TOOL_CAPACITY: "Llenado de mezcla",
        TOOL_DENSITY: "Densidad",
        TOOL_MIXCONFIG: "Config. de mezcla",
        LABEL_PPO2_LIMIT: "Límite ppO2",
        LABEL_TRIMIX: "Trimix",
        LABEL_EAD_DEPTH: "Profundidad EAD",
        LABEL_O2: "O2",
        LABEL_HE: "He",
        LABEL_PPO2_FOR_MOD: "ppO2 para MOD",
        LABEL_SETPOINT_CCR: "Setpoint (CCR)",
        LABEL_MIX_PRESSURE_UNITS: "Unidades de presión",
        LABEL_MIX_TEMP_UNITS: "Unidades de temperatura",
        LABEL_MIX_TEMPERATURE: "Temperatura",
        LABEL_BANKED_GAS: "Gas de banco",
        OPT_TEMP_C: "C",
        OPT_TEMP_F: "F",
        OPT_BANKED_AIR: "Aire",
        OPT_BANKED_32: "32",
        RESULT_BEST_MIX: "Mejor mezcla",
        RESULT_MOD: "MOD",
        RESULT_EAD: "EAD",
        RESULT_END: "END",
        RESULT_EADD: "EADD",
        LABEL_OLD_PRESSURE: "Presión vieja",
        LABEL_NEW_PRESSURE: "Presión nueva",
        LABEL_OLD_O2: "O2 viejo",
        LABEL_NEW_O2: "O2 nuevo",
        LABEL_OLD_HE: "He viejo",
        LABEL_NEW_HE: "He nuevo",
        LABEL_ADD_FIRST: "Añadir primero",
        OPT_ADD_HE_FIRST: "He",
        OPT_ADD_O2_FIRST: "O2",
        LABEL_START_PRESSURE: "Presión inicial",
        LABEL_START_O2: "O2 inicial",
        LABEL_START_HE: "He inicial",
        LABEL_END_PRESSURE: "Presión final",
        LABEL_END_O2: "O2 final",
        LABEL_END_HE: "He final",
        LABEL_FILL_ORDER: "Orden de llenado",
        OPT_HE_FIRST: "He primero",
        OPT_O2_FIRST: "O2 primero",
        RESULT_ADD_O2: "Añadir O2",
        RESULT_ADD_AIR: "Añadir aire",
        RESULT_ADD_32: "Añadir 32",
        RESULT_ADD_HE: "Añadir He",
        RESULT_TEST_O2: "Medir O2",
        LABEL_TOPUP_WITH_O2: "Rellenar con O2",
        LABEL_TOPUP_WITH_HE: "Rellenar con He",
        RESULT_TOPUP_RESULT: "Resultado",
        LABEL_CURRENT_PRESSURE: "Presión actual",
        LABEL_CURRENT_O2: "O2 actual",
        LABEL_CURRENT_HE: "He actual",
        LABEL_ADD_PRESSURE: "Añadir presión",
        LABEL_TOP_GAS_O2: "O2 del gas de relleno",
        LABEL_TOP_GAS_HE: "He del gas de relleno",
        RESULT_FINAL_O2: "O2 final %",
        RESULT_FINAL_HE: "He final %",
        RESULT_FINAL_PRESSURE: "Presión final",
        LABEL_SUPPLY_TANK: "Botella de suministro",
        LABEL_WATER_CAPACITY: "Capacidad de agua",
        LABEL_PRESSURE: "Presión",
        LABEL_RECEIVING_TANK: "Botella receptora",
        RESULT_EQ_PRESSURE: "Presión equilibrada",
        LABEL_SUPPLY_START_PRESSURE: "Presión inicial de suministro",
        LABEL_SUPPLY_SIZE: "Tamaño de suministro",
        LABEL_RECEIVE_SIZE: "Tamaño receptor",
        LABEL_RECEIVE_START_PRESSURE: "Presión inicial del receptor",
        LABEL_RECEIVE_ADD_PRESSURE: "Presión a añadir al receptor",
        BTN_EQUALIZE: "Igualar",
        BTN_REPEAT: "Repetir",
        RESULT_SUPPLY_RESULT: "Resultado suministro",
        RESULT_RECEIVE_RESULT: "Resultado receptor",
        WARN_MIXFILL_LOW_SUPPLY: "El resultado del suministro es menor que el del receptor.",
        LABEL_DENSITY_MODE: "Modo",
        OPT_SP: "SP",
        LABEL_TEMP_MODE: "Temperatura",
        OPT_0C: "0C",
        OPT_20C: "20C",
        WARN_DENSITY_HIGH: "La densidad del gas supera 6.2 g/L — alto riesgo de retención de CO2!",
        WARN_DENSITY_MEDIUM: "Densidad del gas superior a 5.2 g/L — mayor trabajo respiratorio.",
        RESULT_DIVE_HEADER: "Resultado del plan de inmersión #{n}",
        TABLE_ACTION: "Acción",
        TABLE_DEPTH: "Profundidad",
        TABLE_STOP: "Parada",
        TABLE_RUN: "Avance",
        TABLE_MIX: "Mezcla",
        TABLE_PPO2: "pO2",
        TABLE_EAD: "EAD",
        ACTION_DESC: "Des",
        ACTION_LVL: "Niv",
        ACTION_ASC: "Asc",
        ACTION_STP: "Par",
        ACTION_SFC: "Sup",
        BTN_NEXT_DIVE: "SIGUIENTE INMERSIÓN",
        BTN_TEXT_REPORT: "Informe de texto",
        BTN_DEBUG_INFO: "INFO DE DEPURACIÓN AL DESARROLLADOR",
        MODAL_REPORT_TITLE: "Informe del plan de inmersión",
        MODAL_SURFACE_INTERVAL: "Intervalo en superficie",
        UNIT_DAYS: "días",
        UNIT_HOURS: "horas",
        UNIT_MINUTES: "min",
        LABEL_SI_TOTAL: "Total: {n} min",
        MSG_SI_DESCRIPTION: "Establezca el tiempo entre inmersiones. Los tejidos desgasificarán durante este intervalo.",
        BTN_START_NEXT_DIVE: "Iniciar siguiente inmersión",
        AXIS_RUNTIME: "Runtime (min)",
        AXIS_PRESSURE: "Presión (bar)",
        MSG_COPIED: "Plan de inmersión copiado al portapapeles.",
        MSG_COPY_FAILED: "No se pudo copiar al portapapeles.",
        MSG_COPIED_SHORT: "¡Copiado!",
        MSG_TISSUES_RESET: "Tejidos de superficie reiniciados. La próxima inmersión se planificará como #1.",
        ERR_NO_LEVELS: "Añada al menos un nivel de fondo antes de calcular.",
        ERR_NO_RESULT: "No hay inmersión completada para continuar. Calcule primero un plan.",
        ERR_CALC: "Error de cálculo: {error}",
        WARN_PPO2_HI_DETAIL: "ppO2 {val} > {threshold} a {depth}m ({gas})",
        UNIT_M: "m",
        UNIT_FT: "pies",
        UNIT_L: "L",
        UNIT_M_MIN: "m/min",
        UNIT_FT_MIN: "pies/min",
        UNIT_L_MIN: "L/min",
        UNIT_CUFT_MIN: "pie³/min",
        UNIT_G_L: "g/L",
        UNIT_LITERS_WORD: "litros",
        ACTION_DES_SHORT: "Baj",
        ACTION_LVL_SHORT: "Niv",
        ACTION_STP_SHORT: "Par",
        ACTION_SFC_SHORT: "Sup",
        SUMMARY_ELEVATION_LABEL: "Altitud",
        SUMMARY_RUNTIME_LABEL: "Runtime",
        SUMMARY_DECO_LABEL: "Deco",
        SUMMARY_STOPS_LABEL: "Paradas",
        SUMMARY_CNS_LABEL: "CNS",
        SUMMARY_OTU_LABEL: "OTU",
        SUMMARY_GAS_PREFIX: "Gas",
        SUMMARY_GAS_DENSITY: "Densidad de gas",
        SUMMARY_DECO_ZONE: "Zona de deco",
        SUMMARY_GF_LABEL: "GF",
        CHART_XAXIS_TIME: "Tiempo ({u})",
        CHART_YAXIS_DEPTH: "Profundidad ({u})",
        CHART_TITLE_DEPTH: "Profundidad {d}{u}",
        CHART_SERIES_DEPTH: "Profundidad",
        CHART_SERIES_GAS: "Gas",
        CHART_TOOLTIP_TIME: "Tiempo",
        CHART_TOOLTIP_DEPTH: "Profundidad",
        ABOUT_TITLE: "ApexDeco",
        ABOUT_SUBTITLE: "Planificador de descompresión de buceo",
        ABOUT_MATH_TESTS: "Verificación matemática: cada herramienta y cada primitiva de descompresión está cubierta por un test automático con comprobación de tolerancias frente a valores de referencia. Puede ejecutar la suite completa en su navegador:",
        ABOUT_TESTS_LINK: "abrir tests.html",
        ABOUT_ALGORITHMS: "Basado en el algoritmo Bühlmann ZH-L16C con Gradient Factors. Implementa planificación de descompresión para buceo OC y CCR. Incluye herramientas de mezcla de gases.",
        ABOUT_COPYRIGHT: "Copyright © Alexey Vlasov. Licenciado bajo la",
        ABOUT_LICENSE_LINK: "GNU Affero General Public License v3.0 (AGPLv3)",
        ABOUT_WARNING_TITLE: "¡ADVERTENCIA!",
        ABOUT_WARNING_TEXT: "SIEMPRE EXISTE RIESGO DE ENFERMEDAD DESCOMPRESIVA AL BUCEAR. USE ESTE PLANIFICADOR BAJO SU PROPIO RIESGO. SIGA SIEMPRE PRÁCTICAS DE BUCEO SEGURAS Y CONSULTE CON INSTRUCTORES DE BUCEO PROFESIONALES.",
        MSG_DEBUG_COPIED: "Información de depuración copiada al portapapeles.",
        MSG_DEBUG_COPY_FAILED: "No se pudo copiar la información de depuración.",
        MSG_DEBUG_LOADED: "Información de depuración cargada del portapapeles.",
        MSG_DEBUG_LOAD_FAILED: "No se pudo cargar la información de depuración del portapapeles.",
        UNIT_MIN: "min",
        UNIT_BAR: "bar",
        UNIT_PSI: "psi",
        UNIT_CUFT: "pie³",
        UNIT_AIR_RATIO: "× Aire",
        ABOUT_MATH_TESTS_FULL: "Tests de verificación matemática. El motor se valida contra el binario original Android MultiDeco (libmultideco.so). Cada herramienta de mezcla (Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density) y cada primitiva de descompresión (carga Schreiner ZH-L16C, techo por Gradient Factors, volumen crítico VPM-B, setpoint CCR, paradas extendidas, OTU/CNS, comportamiento SLP en agua dulce/salada) está cubierta por un test automático con comprobación de tolerancias frente a los valores de referencia de Android. Puede ejecutar la suite completa en su navegador:",
        ABOUT_ALGORITHMS_FULL: "Basado en el algoritmo Bühlmann ZH-L16C con Gradient Factors. Implementa planificación de descompresión para buceo OC. Incluye herramientas de mezcla de gases: Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density.",
        ABOUT_WARNING_TEXT_FULL: "SIEMPRE EXISTE RIESGO DE ENFERMEDAD DESCOMPRESIVA (ED) EN CUALQUIER PERFIL DE INMERSIÓN, INCLUSO SIGUIENDO EL PLAN PRESCRITO POR LAS TABLAS DE BUCEO. NINGÚN PROCEDIMIENTO O TABLA EVITARÁ LA POSIBILIDAD DE ED O TOXICIDAD POR OXÍGENO. La fisiología individual puede variar de un día a otro. Se recomienda encarecidamente mantenerse bien dentro de los límites de exposición proporcionados por el planificador para minimizar el riesgo de ED.",
        RESULT_GAS_USAGE: "Consumo de gas",
        RESULT_TH_VOLUME: "Volumen",
        RESULT_TH_24Lx2: "24L x2",
        RESULT_PP_TITLE: "Presiones parciales de gases",
        CHART_XAXIS_RUNTIME: "Tiempo total (min)",
        CHART_YAXIS_PRESSURE: "Presión (bar)",
        CHART_COMP: "Comp {n}",
        RESULT_GRID_PLAN: "Plan detallado",
        TH_ACTION: "Acción",
        TH_DEPTH: "Prof.",
        TH_TIME: "Tiempo",
        TH_RUNTIME: "RunTime",
        TH_O2: "O2",
        TH_HE: "He",
        TH_SETPOINT: "Setpoint",
        TH_PPO2: "pO2",
        TH_EAD: "EAD",
        TH_END: "END",
        TH_CNS: "CNS",
        TH_OTU: "OTU",
        TH_SEG: "Seg",
        TH_GAS: "Gas",
        ACTION_DESCENT: "Descenso",
        ACTION_LEVEL: "Nivel",
        ACTION_ASCENT: "Ascenso",
        ACTION_STOP: "Parada",
        ACTION_SURFACE: "Superficie",
        ACTION_STOP_SHORT: "Par",
        ACTION_DESC_SHORT: "Desc",
        ACTION_ASC_SHORT: "Asc",
        ACTION_BOTTOM_SHORT: "Fondo",
        ACTION_SURF_SHORT: "Sup",
        RESULT_BAILOUT_PLAN: "Plan de bailout — {model}",
        RESULT_BAILOUT_GAS_REQ: "Gas de bailout requerido",
        REPORT_TITLE: "ApexDeco - Plan de inmersión",
        REPORT_CIRCUIT: "Circuito",
        REPORT_MODEL: "Modelo",
        REPORT_UNITS: "Unidades",
        REPORT_UNITS_METRIC: "Métrico",
        REPORT_UNITS_IMPERIAL: "Imperial",
        REPORT_WATER_SALT: "Agua salada",
        REPORT_WATER_FRESH: "Agua dulce",
        REPORT_BOTTOM_LEVELS: "Niveles de fondo:",
        REPORT_DECO_MIXES: "Mezclas de descompresión:",
        REPORT_PLAN: "Plan:",
        REPORT_TH_SEGMENT: "Segmento",
        REPORT_TH_DEPTH: "Profundidad",
        REPORT_TH_TIME: "Tiempo",
        REPORT_TH_RUN: "Run",
        REPORT_TH_GAS: "Gas",
        REPORT_TOTAL_RUNTIME: "Tiempo total",
        REPORT_OTU: "OTU",
        REPORT_CNS: "CNS",
        WARN_INVALID_MIX: "Mezcla no válida — verifique los valores.",
        GAS_TRIMIX: "Trimix",
        GAS_NITROX: "Nitrox",
        CONFIRM_RESET: "¿Restablecer todos los ajustes a los valores por defecto?",
        UNIT_BAR_OC: "bar (0 = OC)",
        UNIT_MIN_OFF: "min (0 = off)"
    },
    zh: {
        APP_TITLE: "ApexDeco",
        CHART_NO_HE: "本次潜水未使用氦气 — 无需排气。",
        CHART_SUPERSAT_TITLE: "组织间隔气体张力",
        CHART_MODE_SUPERSAT: "过饱和",
        CHART_MODE_N2: "N2 排气",
        CHART_MODE_HE: "He 排气",
        CHART_MODE_SURF: "出水排气",
        CHART_TITLE_SUPERSAT: "组织过饱和：Ptis - Pamb",
        CHART_TITLE_N2: "N2 排气梯度：pN2 - pAlv*fN2",
        CHART_TITLE_HE: "He 排气梯度：pHe",
        CHART_TITLE_SURF: "出水排气：Ptis - Psurf",
        CHART_X_RUNTIME: "运行时间（分）",
        CHART_COMP_MAX: "最大",
        CHART_COMP_ALL: "全部",
        BTN_NAV_PLAN: "计划",
        BTN_NAV_HELP: "帮助",
        BTN_NAV_SETTINGS: "设置",
        BTN_NAV_TOOLS: "工具",
        CARD_BOTTOM_MIX: "底部气体与过渡气",
        CARD_DECO_MIXES: "减压气",
        BTN_ADD_LEVEL: "+ 添加层级",
        BTN_ADD_DECO: "+ 添加减压气",
        BTN_DELETE: "删除",
        BTN_CALCULATE: "计算",
        BTN_RESET_TISSUES: "重置水面组织",
        MSG_NO_BOTTOM_LEVELS: "没有底部层级。点击 + 添加层级。",
        MSG_NO_DECO_MIXES: "没有减压气。点击 + 添加减压气。",
        MODAL_TITLE_ADD_LEVEL: "添加底部气体与过渡气",
        MODAL_TITLE_EDIT_LEVEL: "编辑底部气体与过渡气",
        MODAL_TITLE_ADD_DECO: "添加减压气",
        MODAL_TITLE_EDIT_DECO: "编辑减压气",
        LABEL_DEPTH: "深度",
        LABEL_TIME_MIN: "时间（分钟）",
        LABEL_O2_PERCENT: "O2 %",
        LABEL_HE_PERCENT: "He %",
        LABEL_DEPTH_CHANGE_OVERRIDE: "切换深度覆盖",
        LABEL_SETPOINT: "设定点",
        LABEL_OC_OR_SCR: "OC 或 SCR 阶段:",
        BTN_SAVE: "保存",
        BTN_CANCEL: "取消",
        BTN_OK: "确定",
        BTN_COPY: "复制",
        BTN_CLOSE: "关闭",
        ERR_O2_HE_EXCEED: "O2 + He 不能超过 100%",
        ERR_INVALID_DECO_SWITCH_DEPTH: "请输入有效的减压气体切换深度。",
        CARD_APPEARANCE: "外观",
        LABEL_LANGUAGE: "语言",
        LABEL_INTERFACE_STYLE: "界面风格",
        OPT_LIGHT_THEME: "浅色主题",
        OPT_DARK_THEME: "深色主题",
        CARD_MODEL_SETTINGS: "模型设置",
        LABEL_CIRCUIT: "回路",
        OPT_OC: "OC",
        OPT_CCR: "CCR",
        LABEL_DECO_MODEL: "减压模型",
        LABEL_CONSERVATISM: "保守度",
        LABEL_GF_LO: "GF Lo",
        LABEL_GF_HI: "GF Hi",
        LABEL_O2_NARCOTIC: "O2 具麻醉性",
        OPT_YES: "是",
        OPT_NO: "否",
        CARD_UNIT_SETTINGS: "单位设置",
        LABEL_DEPTH_UNITS: "深度单位",
        OPT_METER: "米",
        OPT_FEET: "英尺",
        LABEL_WATER_TYPE: "水类型",
        OPT_SALT: "海水",
        OPT_FRESH: "淡水",
        LABEL_ALTITUDE: "海拔（米）",
        LABEL_ACCLIMATIZED: "已适应（米）",
        LABEL_GAS_VOLUME: "气体体积",
        OPT_LITER: "升",
        OPT_CUFT: "立方英尺",
        LABEL_PRESSURE_UNITS: "压力单位",
        LABEL_GAUGE_TYPE: "压力表类型",
        OPT_SIMPLE: "简易",
        OPT_DIGITAL: "数字",
        LABEL_TEMPERATURE: "温度",
        CARD_RATES: "下潜 / 上升速率",
        LABEL_DESCENT_RATE: "下潜速率",
        LABEL_ASCENT_RATE: "上升速率",
        LABEL_DECO_ASCENT_RATE: "减压上升速率",
        LABEL_SURFACE_ASCENT_RATE: "出水上升速率",
        CARD_DECO_STOPS: "减压停留设置",
        LABEL_STEP_SIZE: "停留步长",
        LABEL_LAST_STOP_OC: "最后停留 (OC)",
        LABEL_LAST_STOP_CCR: "最后停留 (CCR)",
        LABEL_MIN_STOP_TIME: "最短停留时间",
        OPT_STOP_1MIN: "1 分钟",
        OPT_STOP_30S: "30 秒",
        OPT_STOP_10S: "10 秒",
        OPT_STOP_1S: "1 秒",
        LABEL_PPO2_SWAP: "减压换气 ppO2",
        LABEL_PPO2_MID_MIX: "ppO2 28-45% 混合气",
        LABEL_PPO2_HIGH_MIX: "ppO2 45-99% 混合气",
        LABEL_PPO2_BOTTOM_MAX: "底部 ppO2 最大值",
        LABEL_O2_MAX_DEPTH: "O2 100% 最大深度",
        LABEL_FIRST_STOP_30S: "首次停留 30 秒",
        LABEL_FIRST_STOP_DBL: "首次停留双倍步长",
        OPT_OFF: "关",
        OPT_ON: "开",
        CARD_CCR_SETTINGS: "CCR 设置",
        LABEL_DEFAULT_SETPOINT: "默认设定点",
        LABEL_SP_UNITS: "SP 单位",
        CARD_RMV: "RMV / 气体规划",
        LABEL_BOTTOM_RMV: "底部 RMV",
        LABEL_DECO_RMV: "减压 RMV",
        LABEL_CCR_DIL_RMV: "CCR稀释剂代谢率",
        CARD_EXTENDED_STOPS: "延长停留",
        LABEL_EXTENDED_STOPS: "延长停留",
        LABEL_ADD_TIME_STOP: "增加停留时间",
        LABEL_ALL_MIX_CHANGES: "所有换气",
        LABEL_O2_WINDOW: "O2 窗口效应",
        MSG_EXT_STOPS_DESC: "切换减压气时包含延长停留",
        LABEL_EXT_SHALLOW: "7..30 米",
        LABEL_EXT_DEEP: "30 + 米",
        CARD_WARNINGS: "警告阈值",
        LABEL_WARN_PPO2_HI: "ppO2 高",
        LABEL_WARN_PPO2_LO: "ppO2 低",
        LABEL_WARN_CNS: "CNS % 超过",
        LABEL_WARN_OTU: "OTU 超过",
        LABEL_WARN_IBCD_N2: "IBCD N2",
        LABEL_WARN_IBCD_HE: "IBCD He",
        LABEL_WARN_CCR_DIL: "CCR 稀释气检查",
        MSG_CCR_DIL_CHECK: "对比稀释气 ppO2 与设定点",
        CARD_BAILOUT: "Bailout 设置",
        LABEL_BAILOUT_PLAN: "Bailout 方案",
        LABEL_BAILOUT_MODEL: "Bailout 模型",
        LABEL_BAILOUT_GF_LO: "Bailout GF Lo",
        LABEL_BAILOUT_GF_HI: "Bailout GF Hi",
        LABEL_BAILOUT_RMV: "Bailout RMV",
        LABEL_EXTRA_BOTTOM_MIN: "额外底部分钟",
        LABEL_EXTRA_TIME_MIN: "额外时间（分钟）",
        LABEL_BAILOUT_GFS: "Bailout GFS Hi",
        LABEL_BAILOUT_DIVE_NUM: "Bailout 潜水 #",
        LABEL_CAVE_TYPE_BAIL: "洞穴 Bailout 类型",
        LABEL_RETURN_PORTION: "返程比例",
        CARD_MULTI_DIVE: "水面间隔 / 多次潜水",
        LABEL_2WEEK_OTU: "两周 OTU",
        UNIT_CUMULATIVE: "累计",
        LABEL_TRAVEL_O2: "过渡气 O2%",
        LABEL_TRAVEL_HE: "过渡气 He%",
        BTN_RESET_CONFIG: "重置配置",
        BTN_LOAD_DEBUG_INFO: "加载调试信息",
        HOF_TITLE: "捐赠名人堂",
        HOF_BTN_DONATE: "如何捐赠",
        HOF_BTN_CALL: "致电开发者",
        HOF_FOUNDERS: "创始人捐赠区",
        HOF_GOLD: "黄金捐赠区",
        HOF_SILVER: "白银捐赠区",
        HOF_BRONZE: "青铜捐赠区",
        TOOL_BESTMIX: "最佳混合气",
        TOOL_EADMOD: "EAD, MOD, END",
        TOOL_NITROX: "混合 Nitrox",
        TOOL_TRIMIX: "混合 Trimix",
        TOOL_TOPUP: "混合补气",
        TOOL_CAPACITY: "混合充填",
        TOOL_DENSITY: "密度",
        TOOL_MIXCONFIG: "混气设置",
        LABEL_PPO2_LIMIT: "ppO2 上限",
        LABEL_TRIMIX: "三混气",
        LABEL_EAD_DEPTH: "EAD 深度",
        LABEL_O2: "O2",
        LABEL_HE: "He",
        LABEL_PPO2_FOR_MOD: "用于 MOD 的 ppO2",
        LABEL_SETPOINT_CCR: "设定点 (CCR)",
        LABEL_MIX_PRESSURE_UNITS: "压力单位",
        LABEL_MIX_TEMP_UNITS: "温度单位",
        LABEL_MIX_TEMPERATURE: "温度",
        LABEL_BANKED_GAS: "储备气体",
        OPT_TEMP_C: "C",
        OPT_TEMP_F: "F",
        OPT_BANKED_AIR: "空气",
        OPT_BANKED_32: "32",
        RESULT_BEST_MIX: "最佳混合气",
        RESULT_MOD: "MOD",
        RESULT_EAD: "EAD",
        RESULT_END: "END",
        RESULT_EADD: "EADD",
        LABEL_OLD_PRESSURE: "旧压力",
        LABEL_NEW_PRESSURE: "新压力",
        LABEL_OLD_O2: "旧 O2",
        LABEL_NEW_O2: "新 O2",
        LABEL_OLD_HE: "旧 He",
        LABEL_NEW_HE: "新 He",
        LABEL_ADD_FIRST: "先添加",
        OPT_ADD_HE_FIRST: "He",
        OPT_ADD_O2_FIRST: "O2",
        LABEL_START_PRESSURE: "起始压力",
        LABEL_START_O2: "起始 O2",
        LABEL_START_HE: "起始 He",
        LABEL_END_PRESSURE: "最终压力",
        LABEL_END_O2: "最终 O2",
        LABEL_END_HE: "最终 He",
        LABEL_FILL_ORDER: "充填顺序",
        OPT_HE_FIRST: "先 He",
        OPT_O2_FIRST: "先 O2",
        RESULT_ADD_O2: "加入 O2",
        RESULT_ADD_AIR: "加入空气",
        RESULT_ADD_32: "加入 32",
        RESULT_ADD_HE: "加入 He",
        RESULT_TEST_O2: "测量 O2",
        LABEL_TOPUP_WITH_O2: "补入 O2",
        LABEL_TOPUP_WITH_HE: "补入 He",
        RESULT_TOPUP_RESULT: "结果",
        LABEL_CURRENT_PRESSURE: "当前压力",
        LABEL_CURRENT_O2: "当前 O2",
        LABEL_CURRENT_HE: "当前 He",
        LABEL_ADD_PRESSURE: "添加压力",
        LABEL_TOP_GAS_O2: "补气 O2",
        LABEL_TOP_GAS_HE: "补气 He",
        RESULT_FINAL_O2: "最终 O2 %",
        RESULT_FINAL_HE: "最终 He %",
        RESULT_FINAL_PRESSURE: "最终压力",
        LABEL_SUPPLY_TANK: "供气瓶",
        LABEL_WATER_CAPACITY: "水容积",
        LABEL_PRESSURE: "压力",
        LABEL_RECEIVING_TANK: "受气瓶",
        RESULT_EQ_PRESSURE: "均压后压力",
        LABEL_SUPPLY_START_PRESSURE: "供气起始压力",
        LABEL_SUPPLY_SIZE: "供气容量",
        LABEL_RECEIVE_SIZE: "受气容量",
        LABEL_RECEIVE_START_PRESSURE: "受气起始压力",
        LABEL_RECEIVE_ADD_PRESSURE: "受气增加压力",
        BTN_EQUALIZE: "均压",
        BTN_REPEAT: "重复",
        RESULT_SUPPLY_RESULT: "供气结果",
        RESULT_RECEIVE_RESULT: "受气结果",
        WARN_MIXFILL_LOW_SUPPLY: "供气结果低于受气结果。",
        LABEL_DENSITY_MODE: "模式",
        OPT_SP: "SP",
        LABEL_TEMP_MODE: "温度",
        OPT_0C: "0C",
        OPT_20C: "20C",
        WARN_DENSITY_HIGH: "气体密度超过 6.2 g/L — CO2 潴留风险高！",
        WARN_DENSITY_MEDIUM: "气体密度高于 5.2 g/L — 呼吸做功增加。",
        RESULT_DIVE_HEADER: "第 {n} 次潜水计划结果",
        TABLE_ACTION: "动作",
        TABLE_DEPTH: "深度",
        TABLE_STOP: "停留",
        TABLE_RUN: "进行",
        TABLE_MIX: "气体",
        TABLE_PPO2: "pO2",
        TABLE_EAD: "EAD",
        ACTION_DESC: "下",
        ACTION_LVL: "平",
        ACTION_ASC: "上",
        ACTION_STP: "停",
        ACTION_SFC: "面",
        BTN_NEXT_DIVE: "下一次潜水",
        BTN_TEXT_REPORT: "文本报告",
        BTN_DEBUG_INFO: "调试信息发送给开发者",
        MODAL_REPORT_TITLE: "潜水计划报告",
        MODAL_SURFACE_INTERVAL: "水面间隔",
        UNIT_DAYS: "天",
        UNIT_HOURS: "小时",
        UNIT_MINUTES: "分",
        LABEL_SI_TOTAL: "总计：{n} 分",
        MSG_SI_DESCRIPTION: "设置两次潜水之间的时间。在此间隔期间组织将进行脱气。",
        BTN_START_NEXT_DIVE: "开始下一次潜水",
        AXIS_RUNTIME: "Runtime（分钟）",
        AXIS_PRESSURE: "压力 (bar)",
        MSG_COPIED: "潜水计划已复制到剪贴板。",
        MSG_COPY_FAILED: "复制到剪贴板失败。",
        MSG_COPIED_SHORT: "已复制！",
        MSG_TISSUES_RESET: "水面组织已重置。下次潜水将作为第 1 次潜水计算。",
        ERR_NO_LEVELS: "计算前请至少添加一个底部层级。",
        ERR_NO_RESULT: "没有可继续的已完成潜水。请先计算一个潜水计划。",
        ERR_CALC: "计算错误：{error}",
        WARN_PPO2_HI_DETAIL: "ppO2 {val} > {threshold} 在 {depth}m ({gas})",
        UNIT_M: "m",
        UNIT_FT: "英尺",
        UNIT_L: "L",
        UNIT_M_MIN: "m/min",
        UNIT_FT_MIN: "英尺/分",
        UNIT_L_MIN: "L/min",
        UNIT_CUFT_MIN: "立方英尺/分",
        UNIT_G_L: "g/L",
        UNIT_LITERS_WORD: "升",
        ACTION_DES_SHORT: "下潜",
        ACTION_LVL_SHORT: "平潜",
        ACTION_STP_SHORT: "停留",
        ACTION_SFC_SHORT: "水面",
        SUMMARY_ELEVATION_LABEL: "海拔",
        SUMMARY_RUNTIME_LABEL: "总时间",
        SUMMARY_DECO_LABEL: "减压",
        SUMMARY_STOPS_LABEL: "停留次数",
        SUMMARY_CNS_LABEL: "CNS",
        SUMMARY_OTU_LABEL: "OTU",
        SUMMARY_GAS_PREFIX: "气体",
        SUMMARY_GAS_DENSITY: "气体密度",
        SUMMARY_DECO_ZONE: "减压区",
        SUMMARY_GF_LABEL: "GF",
        CHART_XAXIS_TIME: "时间 ({u})",
        CHART_YAXIS_DEPTH: "深度 ({u})",
        CHART_TITLE_DEPTH: "深度 {d}{u}",
        CHART_SERIES_DEPTH: "深度",
        CHART_SERIES_GAS: "气体",
        CHART_TOOLTIP_TIME: "时间",
        CHART_TOOLTIP_DEPTH: "深度",
        ABOUT_TITLE: "ApexDeco",
        ABOUT_SUBTITLE: "潜水减压计划器",
        ABOUT_MATH_TESTS: "数学验证：每个工具和每个减压原语都由自动化测试覆盖，并对照参考值进行容差检查。您可以在浏览器中运行完整测试套件：",
        ABOUT_TESTS_LINK: "打开 tests.html",
        ABOUT_ALGORITHMS: "基于 Bühlmann ZH-L16C 算法与 Gradient Factors。实现 OC 与 CCR 潜水的减压计划，并包含气体混合工具。",
        ABOUT_COPYRIGHT: "版权所有 © Alexey Vlasov。采用以下许可证：",
        ABOUT_LICENSE_LINK: "GNU Affero General Public License v3.0 (AGPLv3)",
        ABOUT_WARNING_TITLE: "警告！",
        ABOUT_WARNING_TEXT: "潜水始终存在减压病风险。使用本计划器须自担风险。务必遵循安全潜水规范并咨询专业潜水教练。",
        MSG_DEBUG_COPIED: "调试信息已复制到剪贴板。",
        MSG_DEBUG_COPY_FAILED: "复制调试信息到剪贴板失败。",
        MSG_DEBUG_LOADED: "调试信息已从剪贴板加载。",
        MSG_DEBUG_LOAD_FAILED: "从剪贴板加载调试信息失败。",
        UNIT_MIN: "分钟",
        UNIT_BAR: "巴",
        UNIT_PSI: "psi",
        UNIT_CUFT: "立方英尺",
        UNIT_AIR_RATIO: "× 空气",
        ABOUT_MATH_TESTS_FULL: "数学验证测试。引擎已针对原始 Android MultiDeco 二进制 (libmultideco.so) 进行验证。每个气体混合工具 (Best Mix、EAD/MOD、Nitrox、Trimix、Top-up、Capacity、Density) 及每项减压原语 (ZH-L16C Schreiner 负荷、Gradient Factor 天花板、VPM-B 临界体积、CCR 设定点、扩展停留、OTU/CNS、淡水/海水 SLP 行为) 均由自动化测试覆盖，并与 Android 参考值进行容差对比。您可以在浏览器中运行完整测试套件：",
        ABOUT_ALGORITHMS_FULL: "基于 Bühlmann ZH-L16C 算法与 Gradient Factors。实现开循环 (OC) 潜水的减压计划。包含气体混合工具：Best Mix、EAD/MOD、Nitrox、Trimix、Top-up、Capacity、Density。",
        ABOUT_WARNING_TEXT_FULL: "任何潜水剖面都始终存在减压病 (DCS) 风险，即使严格遵循潜水表规定的计划也是如此。没有任何程序或潜水表能够消除 DCS 或氧气中毒的可能性！个人的生理状况可能因日而异。强烈建议您始终保持在本计划器提供的暴露限值以内，以尽量降低 DCS 风险。",
        RESULT_GAS_USAGE: "气体消耗",
        RESULT_TH_VOLUME: "体积",
        RESULT_TH_24Lx2: "24L x2",
        RESULT_PP_TITLE: "气体分压",
        CHART_XAXIS_RUNTIME: "运行时间 (分钟)",
        CHART_YAXIS_PRESSURE: "压力 (巴)",
        CHART_COMP: "舱 {n}",
        RESULT_GRID_PLAN: "详细计划",
        TH_ACTION: "动作",
        TH_DEPTH: "深度",
        TH_TIME: "时间",
        TH_RUNTIME: "运行时间",
        TH_O2: "O2",
        TH_HE: "He",
        TH_SETPOINT: "设定点",
        TH_PPO2: "pO2",
        TH_EAD: "EAD",
        TH_END: "END",
        TH_CNS: "CNS",
        TH_OTU: "OTU",
        TH_SEG: "段",
        TH_GAS: "气体",
        ACTION_DESCENT: "下潜",
        ACTION_LEVEL: "水平",
        ACTION_ASCENT: "上升",
        ACTION_STOP: "停留",
        ACTION_SURFACE: "水面",
        ACTION_STOP_SHORT: "停",
        ACTION_DESC_SHORT: "下",
        ACTION_ASC_SHORT: "上",
        ACTION_BOTTOM_SHORT: "底",
        ACTION_SURF_SHORT: "面",
        RESULT_BAILOUT_PLAN: "备用计划 — {model}",
        RESULT_BAILOUT_GAS_REQ: "备用气体需求",
        REPORT_TITLE: "ApexDeco - 潜水计划",
        REPORT_CIRCUIT: "回路",
        REPORT_MODEL: "模型",
        REPORT_UNITS: "单位",
        REPORT_UNITS_METRIC: "公制",
        REPORT_UNITS_IMPERIAL: "英制",
        REPORT_WATER_SALT: "海水",
        REPORT_WATER_FRESH: "淡水",
        REPORT_BOTTOM_LEVELS: "底部层次:",
        REPORT_DECO_MIXES: "减压混合气:",
        REPORT_PLAN: "计划:",
        REPORT_TH_SEGMENT: "段",
        REPORT_TH_DEPTH: "深度",
        REPORT_TH_TIME: "时间",
        REPORT_TH_RUN: "累计",
        REPORT_TH_GAS: "气体",
        REPORT_TOTAL_RUNTIME: "总时间",
        REPORT_OTU: "OTU",
        REPORT_CNS: "CNS",
        WARN_INVALID_MIX: "混合气无效——请检查数值。",
        GAS_TRIMIX: "三混气",
        GAS_NITROX: "高氧",
        CONFIRM_RESET: "将所有设置恢复为默认值？",
        UNIT_BAR_OC: "巴 (0 = OC)",
        UNIT_MIN_OFF: "分钟 (0 = 关闭)"
    },
    hi: {
        APP_TITLE: "ApexDeco",
        CHART_NO_HE: "इस गोते में हीलियम नहीं है — ऑफ़़गैस करने के लिए कुछ नहीं।",
        CHART_SUPERSAT_TITLE: "ऊतक डिब्बों में गैस तनाव",
        CHART_MODE_SUPERSAT: "अति-संतृप्ति",
        CHART_MODE_N2: "N2 ऑफ़़गैस",
        CHART_MODE_HE: "He ऑफ़़गैस",
        CHART_MODE_SURF: "सतह ऑफ़़गैस",
        CHART_TITLE_SUPERSAT: "ऊतक अति-संतृप्ति: कुल Ptis - Pamb",
        CHART_TITLE_N2: "N2 ऑफ़़गैस ग्रेडिएंट: pN2 - pAlv*fN2",
        CHART_TITLE_HE: "He ऑफ़़गैस ग्रेडिएंट: pHe",
        CHART_TITLE_SURF: "सतह ऑफ़़गैस: Ptis - Psurf",
        CHART_X_RUNTIME: "रनटाइम (मिनट)",
        CHART_COMP_MAX: "अधिकतम",
        CHART_COMP_ALL: "सभी",
        BTN_NAV_PLAN: "योजना",
        BTN_NAV_HELP: "मदद",
        BTN_NAV_SETTINGS: "सेटिंग्स",
        BTN_NAV_TOOLS: "उपकरण",
        CARD_BOTTOM_MIX: "तल गैस और यात्रा गैस",
        CARD_DECO_MIXES: "डिकंप्रेशन गैसें",
        BTN_ADD_LEVEL: "+ स्तर जोड़ें",
        BTN_ADD_DECO: "+ डिको जोड़ें",
        BTN_DELETE: "हटाएँ",
        BTN_CALCULATE: "गणना करें",
        BTN_RESET_TISSUES: "सतह ऊतक रीसेट करें",
        MSG_NO_BOTTOM_LEVELS: "कोई तल स्तर नहीं। + स्तर जोड़ें पर क्लिक करें।",
        MSG_NO_DECO_MIXES: "कोई डिको गैस नहीं। + डिको जोड़ें पर क्लिक करें।",
        MODAL_TITLE_ADD_LEVEL: "तल गैस और यात्रा गैस जोड़ें",
        MODAL_TITLE_EDIT_LEVEL: "तल गैस और यात्रा गैस संपादित करें",
        MODAL_TITLE_ADD_DECO: "डिको गैस जोड़ें",
        MODAL_TITLE_EDIT_DECO: "डिको गैस संपादित करें",
        LABEL_DEPTH: "गहराई",
        LABEL_TIME_MIN: "समय (मिनट)",
        LABEL_O2_PERCENT: "O2 %",
        LABEL_HE_PERCENT: "He %",
        LABEL_DEPTH_CHANGE_OVERRIDE: "स्विच गहराई ओवरराइड",
        LABEL_SETPOINT: "सेटपॉइंट",
        LABEL_OC_OR_SCR: "OC या SCR चरण:",
        BTN_SAVE: "सहेजें",
        BTN_CANCEL: "रद्द करें",
        BTN_OK: "ठीक है",
        BTN_COPY: "कॉपी करें",
        BTN_CLOSE: "बंद करें",
        ERR_O2_HE_EXCEED: "O2 + He 100% से अधिक नहीं हो सकते",
        ERR_INVALID_DECO_SWITCH_DEPTH: "मान्य डेको गैस स्विच गहराई दर्ज करें।",
        CARD_APPEARANCE: "स्वरूप",
        LABEL_LANGUAGE: "भाषा",
        LABEL_INTERFACE_STYLE: "इंटरफ़ेस शैली",
        OPT_LIGHT_THEME: "हल्की थीम",
        OPT_DARK_THEME: "गहरी थीम",
        CARD_MODEL_SETTINGS: "मॉडल सेटिंग्स",
        LABEL_CIRCUIT: "सर्किट",
        OPT_OC: "OC",
        OPT_CCR: "CCR",
        LABEL_DECO_MODEL: "डिको मॉडल",
        LABEL_CONSERVATISM: "सुरक्षात्मकता",
        LABEL_GF_LO: "GF Lo",
        LABEL_GF_HI: "GF Hi",
        LABEL_O2_NARCOTIC: "O2 नारकोटिक",
        OPT_YES: "हाँ",
        OPT_NO: "नहीं",
        CARD_UNIT_SETTINGS: "इकाई सेटिंग्स",
        LABEL_DEPTH_UNITS: "गहराई की इकाइयाँ",
        OPT_METER: "मीटर",
        OPT_FEET: "फ़ीट",
        LABEL_WATER_TYPE: "पानी का प्रकार",
        OPT_SALT: "खारा",
        OPT_FRESH: "मीठा",
        LABEL_ALTITUDE: "ऊँचाई (मी)",
        LABEL_ACCLIMATIZED: "अनुकूलित (मी)",
        LABEL_GAS_VOLUME: "गैस आयतन",
        OPT_LITER: "लीटर",
        OPT_CUFT: "CuFt",
        LABEL_PRESSURE_UNITS: "दाब इकाइयाँ",
        LABEL_GAUGE_TYPE: "गेज प्रकार",
        OPT_SIMPLE: "सरल",
        OPT_DIGITAL: "डिजिटल",
        LABEL_TEMPERATURE: "तापमान",
        CARD_RATES: "अवतरण / आरोहण दर",
        LABEL_DESCENT_RATE: "अवतरण दर",
        LABEL_ASCENT_RATE: "आरोहण दर",
        LABEL_DECO_ASCENT_RATE: "डिको आरोहण दर",
        LABEL_SURFACE_ASCENT_RATE: "सतह तक आरोहण दर",
        CARD_DECO_STOPS: "डिको स्टॉप सेटिंग्स",
        LABEL_STEP_SIZE: "स्टेप आकार",
        LABEL_LAST_STOP_OC: "अंतिम स्टॉप (OC)",
        LABEL_LAST_STOP_CCR: "अंतिम स्टॉप (CCR)",
        LABEL_MIN_STOP_TIME: "न्यूनतम स्टॉप समय",
        OPT_STOP_1MIN: "1 मिनट",
        OPT_STOP_30S: "30 सेकंड",
        OPT_STOP_10S: "10 सेकंड",
        OPT_STOP_1S: "1 सेकंड",
        LABEL_PPO2_SWAP: "ppO2 डिको स्वैप",
        LABEL_PPO2_MID_MIX: "ppO2 28-45% मिश्रण",
        LABEL_PPO2_HIGH_MIX: "ppO2 45-99% मिश्रण",
        LABEL_PPO2_BOTTOM_MAX: "ppO2 तल अधिकतम",
        LABEL_O2_MAX_DEPTH: "O2 100% अधिकतम गहराई",
        LABEL_FIRST_STOP_30S: "पहला स्टॉप 30 सेकंड",
        LABEL_FIRST_STOP_DBL: "पहला स्टॉप दोहरा स्टेप",
        OPT_OFF: "बंद",
        OPT_ON: "चालू",
        CARD_CCR_SETTINGS: "CCR सेटिंग्स",
        LABEL_DEFAULT_SETPOINT: "डिफ़ॉल्ट सेटपॉइंट",
        LABEL_SP_UNITS: "SP इकाइयाँ",
        CARD_RMV: "RMV / गैस योजना",
        LABEL_BOTTOM_RMV: "तल RMV",
        LABEL_DECO_RMV: "डिको RMV",
        LABEL_CCR_DIL_RMV: "CCR डिल चयापचय",
        CARD_EXTENDED_STOPS: "विस्तारित स्टॉप",
        LABEL_EXTENDED_STOPS: "विस्तारित स्टॉप",
        LABEL_ADD_TIME_STOP: "स्टॉप में समय जोड़ें",
        LABEL_ALL_MIX_CHANGES: "सभी मिश्रण परिवर्तन",
        LABEL_O2_WINDOW: "O2 विंडो प्रभाव",
        MSG_EXT_STOPS_DESC: "डिको गैस बदलने पर विस्तारित स्टॉप शामिल करें",
        LABEL_EXT_SHALLOW: "7..30 मी",
        LABEL_EXT_DEEP: "30 + मी",
        CARD_WARNINGS: "चेतावनी सीमाएँ",
        LABEL_WARN_PPO2_HI: "ppO2 उच्च",
        LABEL_WARN_PPO2_LO: "ppO2 निम्न",
        LABEL_WARN_CNS: "CNS % से अधिक",
        LABEL_WARN_OTU: "OTU से अधिक",
        LABEL_WARN_IBCD_N2: "IBCD N2",
        LABEL_WARN_IBCD_HE: "IBCD He",
        LABEL_WARN_CCR_DIL: "CCR डिल्यूएंट जाँच",
        MSG_CCR_DIL_CHECK: "डिल्यूएंट ppO2 की सेटपॉइंट से तुलना करें",
        CARD_BAILOUT: "Bailout सेटिंग्स",
        LABEL_BAILOUT_PLAN: "Bailout योजना",
        LABEL_BAILOUT_MODEL: "Bailout मॉडल",
        LABEL_BAILOUT_GF_LO: "Bailout GF Lo",
        LABEL_BAILOUT_GF_HI: "Bailout GF Hi",
        LABEL_BAILOUT_RMV: "Bailout RMV",
        LABEL_EXTRA_BOTTOM_MIN: "अतिरिक्त तल मिनट",
        LABEL_EXTRA_TIME_MIN: "अतिरिक्त समय (मिनट)",
        LABEL_BAILOUT_GFS: "Bailout GFS Hi",
        LABEL_BAILOUT_DIVE_NUM: "Bailout डाइव #",
        LABEL_CAVE_TYPE_BAIL: "गुफा Bailout प्रकार",
        LABEL_RETURN_PORTION: "वापसी का हिस्सा",
        CARD_MULTI_DIVE: "सतह अंतराल / बहु-डाइव",
        LABEL_2WEEK_OTU: "2-सप्ताह OTU",
        UNIT_CUMULATIVE: "संचयी",
        LABEL_TRAVEL_O2: "यात्रा गैस O2%",
        LABEL_TRAVEL_HE: "यात्रा गैस He%",
        BTN_RESET_CONFIG: "कॉन्फ़िगरेशन रीसेट करें",
        BTN_LOAD_DEBUG_INFO: "डीबग जानकारी लोड करें",
        HOF_TITLE: "दान कीर्ति मंडप",
        HOF_BTN_DONATE: "दान कैसे करें",
        HOF_BTN_CALL: "डेवलपर्स को कॉल करें",
        HOF_FOUNDERS: "संस्थापक दान अनुभाग",
        HOF_GOLD: "स्वर्ण दान अनुभाग",
        HOF_SILVER: "रजत दान अनुभाग",
        HOF_BRONZE: "कांस्य दान अनुभाग",
        TOOL_BESTMIX: "सर्वोत्तम मिश्रण",
        TOOL_EADMOD: "EAD, MOD, END",
        TOOL_NITROX: "नाइट्रोक्स मिक्स",
        TOOL_TRIMIX: "ट्राइमिक्स मिक्स",
        TOOL_TOPUP: "मिक्स टॉपअप",
        TOOL_CAPACITY: "मिक्स फिल",
        TOOL_DENSITY: "घनत्व",
        TOOL_MIXCONFIG: "मिक्स कॉन्फ़िग",
        LABEL_PPO2_LIMIT: "ppO2 सीमा",
        LABEL_TRIMIX: "ट्राइमिक्स",
        LABEL_EAD_DEPTH: "EAD गहराई",
        LABEL_O2: "O2",
        LABEL_HE: "He",
        LABEL_PPO2_FOR_MOD: "MOD के लिए ppO2",
        LABEL_SETPOINT_CCR: "सेटपॉइंट (CCR)",
        LABEL_MIX_PRESSURE_UNITS: "दाब इकाइयाँ",
        LABEL_MIX_TEMP_UNITS: "ताप इकाइयाँ",
        LABEL_MIX_TEMPERATURE: "तापमान",
        LABEL_BANKED_GAS: "बैंक गैस",
        OPT_TEMP_C: "C",
        OPT_TEMP_F: "F",
        OPT_BANKED_AIR: "वायु",
        OPT_BANKED_32: "32",
        RESULT_BEST_MIX: "सर्वोत्तम मिश्रण",
        RESULT_MOD: "MOD",
        RESULT_EAD: "EAD",
        RESULT_END: "END",
        RESULT_EADD: "EADD",
        LABEL_OLD_PRESSURE: "पुराना दाब",
        LABEL_NEW_PRESSURE: "नया दाब",
        LABEL_OLD_O2: "पुराना O2",
        LABEL_NEW_O2: "नया O2",
        LABEL_OLD_HE: "पुराना He",
        LABEL_NEW_HE: "नया He",
        LABEL_ADD_FIRST: "पहले जोड़ें",
        OPT_ADD_HE_FIRST: "He",
        OPT_ADD_O2_FIRST: "O2",
        LABEL_START_PRESSURE: "प्रारंभिक दाब",
        LABEL_START_O2: "प्रारंभिक O2",
        LABEL_START_HE: "प्रारंभिक He",
        LABEL_END_PRESSURE: "अंतिम दाब",
        LABEL_END_O2: "अंतिम O2",
        LABEL_END_HE: "अंतिम He",
        LABEL_FILL_ORDER: "भरने का क्रम",
        OPT_HE_FIRST: "पहले He",
        OPT_O2_FIRST: "पहले O2",
        RESULT_ADD_O2: "O2 जोड़ें",
        RESULT_ADD_AIR: "वायु जोड़ें",
        RESULT_ADD_32: "32 जोड़ें",
        RESULT_ADD_HE: "He जोड़ें",
        RESULT_TEST_O2: "O2 मापें",
        LABEL_TOPUP_WITH_O2: "O2 से टॉपअप",
        LABEL_TOPUP_WITH_HE: "He से टॉपअप",
        RESULT_TOPUP_RESULT: "परिणाम",
        LABEL_CURRENT_PRESSURE: "वर्तमान दाब",
        LABEL_CURRENT_O2: "वर्तमान O2",
        LABEL_CURRENT_HE: "वर्तमान He",
        LABEL_ADD_PRESSURE: "दाब जोड़ें",
        LABEL_TOP_GAS_O2: "टॉप गैस O2",
        LABEL_TOP_GAS_HE: "टॉप गैस He",
        RESULT_FINAL_O2: "अंतिम O2 %",
        RESULT_FINAL_HE: "अंतिम He %",
        RESULT_FINAL_PRESSURE: "अंतिम दाब",
        LABEL_SUPPLY_TANK: "आपूर्ति टैंक",
        LABEL_WATER_CAPACITY: "जल क्षमता",
        LABEL_PRESSURE: "दाब",
        LABEL_RECEIVING_TANK: "प्राप्तकर्ता टैंक",
        RESULT_EQ_PRESSURE: "बराबर किया गया दाब",
        LABEL_SUPPLY_START_PRESSURE: "आपूर्ति प्रारंभ दाब",
        LABEL_SUPPLY_SIZE: "आपूर्ति आकार",
        LABEL_RECEIVE_SIZE: "प्राप्त आकार",
        LABEL_RECEIVE_START_PRESSURE: "प्राप्त प्रारंभ दाब",
        LABEL_RECEIVE_ADD_PRESSURE: "प्राप्त में जोड़ने का दाब",
        BTN_EQUALIZE: "बराबर करें",
        BTN_REPEAT: "दोहराएँ",
        RESULT_SUPPLY_RESULT: "आपूर्ति परिणाम",
        RESULT_RECEIVE_RESULT: "प्राप्त परिणाम",
        WARN_MIXFILL_LOW_SUPPLY: "आपूर्ति परिणाम प्राप्त परिणाम से कम है।",
        LABEL_DENSITY_MODE: "मोड",
        OPT_SP: "SP",
        LABEL_TEMP_MODE: "तापमान",
        OPT_0C: "0C",
        OPT_20C: "20C",
        WARN_DENSITY_HIGH: "गैस घनत्व 6.2 g/L से अधिक है — CO2 प्रतिधारण का उच्च जोखिम!",
        WARN_DENSITY_MEDIUM: "गैस घनत्व 5.2 g/L से अधिक — श्वसन कार्य में वृद्धि।",
        RESULT_DIVE_HEADER: "डाइव #{n} योजना परिणाम",
        TABLE_ACTION: "क्रिया",
        TABLE_DEPTH: "गहराई",
        TABLE_STOP: "स्टॉप",
        TABLE_RUN: "प्रगति",
        TABLE_MIX: "मिश्रण",
        TABLE_PPO2: "pO2",
        TABLE_EAD: "EAD",
        ACTION_DESC: "अव",
        ACTION_LVL: "तल",
        ACTION_ASC: "आर",
        ACTION_STP: "स्ट",
        ACTION_SFC: "सत",
        BTN_NEXT_DIVE: "अगली डाइव",
        BTN_TEXT_REPORT: "टेक्स्ट रिपोर्ट",
        BTN_DEBUG_INFO: "डेवलपर को डीबग जानकारी",
        MODAL_REPORT_TITLE: "डाइव योजना रिपोर्ट",
        MODAL_SURFACE_INTERVAL: "सतह अंतराल",
        UNIT_DAYS: "दिन",
        UNIT_HOURS: "घंटे",
        UNIT_MINUTES: "मिनट",
        LABEL_SI_TOTAL: "कुल: {n} मिनट",
        MSG_SI_DESCRIPTION: "गोताखोरी के बीच का समय निर्धारित करें। इस अंतराल के दौरान ऊतक गैस मुक्त करेंगे।",
        BTN_START_NEXT_DIVE: "अगली डाइव शुरू करें",
        AXIS_RUNTIME: "Runtime (मिनट)",
        AXIS_PRESSURE: "दाब (bar)",
        MSG_COPIED: "डाइव योजना क्लिपबोर्ड पर कॉपी की गई।",
        MSG_COPY_FAILED: "क्लिपबोर्ड पर कॉपी विफल।",
        MSG_COPIED_SHORT: "कॉपी हो गया!",
        MSG_TISSUES_RESET: "सतह ऊतक रीसेट हुए। अगली डाइव #1 के रूप में योजित होगी।",
        ERR_NO_LEVELS: "गणना से पहले कम से कम एक तल स्तर जोड़ें।",
        ERR_NO_RESULT: "जारी रखने के लिए कोई पूर्ण डाइव नहीं। पहले डाइव योजना की गणना करें।",
        ERR_CALC: "गणना त्रुटि: {error}",
        WARN_PPO2_HI_DETAIL: "ppO2 {val} > {threshold} {depth}मी पर ({gas})",
        UNIT_M: "मी",
        UNIT_FT: "फीट",
        UNIT_L: "L",
        UNIT_M_MIN: "मी/मिनट",
        UNIT_FT_MIN: "फीट/मिन",
        UNIT_L_MIN: "L/मिनट",
        UNIT_CUFT_MIN: "घन फीट/मिनट",
        UNIT_G_L: "g/L",
        UNIT_LITERS_WORD: "लीटर",
        ACTION_DES_SHORT: "उतर",
        ACTION_LVL_SHORT: "स्तर",
        ACTION_STP_SHORT: "रुक",
        ACTION_SFC_SHORT: "सत",
        SUMMARY_ELEVATION_LABEL: "ऊँचाई",
        SUMMARY_RUNTIME_LABEL: "रनटाइम",
        SUMMARY_DECO_LABEL: "डीको",
        SUMMARY_STOPS_LABEL: "रुकावटें",
        SUMMARY_CNS_LABEL: "CNS",
        SUMMARY_OTU_LABEL: "OTU",
        SUMMARY_GAS_PREFIX: "गैस",
        SUMMARY_GAS_DENSITY: "गैस घनत्व",
        SUMMARY_DECO_ZONE: "डीको ज़ोन",
        SUMMARY_GF_LABEL: "GF",
        CHART_XAXIS_TIME: "समय ({u})",
        CHART_YAXIS_DEPTH: "गहराई ({u})",
        CHART_TITLE_DEPTH: "गहराई {d}{u}",
        CHART_SERIES_DEPTH: "गहराई",
        CHART_SERIES_GAS: "गैस",
        CHART_TOOLTIP_TIME: "समय",
        CHART_TOOLTIP_DEPTH: "गहराई",
        ABOUT_TITLE: "ApexDeco",
        ABOUT_SUBTITLE: "डाइव डिकंप्रेशन प्लानर",
        ABOUT_MATH_TESTS: "गणित सत्यापन: प्रत्येक उपकरण और प्रत्येक डिकंप्रेशन प्रिमिटिव स्वचालित परीक्षण से आच्छादित है जो संदर्भ मानों के विरुद्ध सहनशीलता जाँच करता है। आप पूरा टेस्ट सूट अपने ब्राउज़र में चला सकते हैं:",
        ABOUT_TESTS_LINK: "tests.html खोलें",
        ABOUT_ALGORITHMS: "Bühlmann ZH-L16C एल्गोरिदम पर आधारित, Gradient Factors के साथ। OC और CCR डाइविंग के लिए डिकंप्रेशन योजना लागू करता है। गैस मिश्रण उपकरण शामिल हैं।",
        ABOUT_COPYRIGHT: "Copyright © Alexey Vlasov. इस लाइसेंस के तहत लाइसेंसीकृत:",
        ABOUT_LICENSE_LINK: "GNU Affero General Public License v3.0 (AGPLv3)",
        ABOUT_WARNING_TITLE: "चेतावनी!",
        ABOUT_WARNING_TEXT: "डाइविंग करते समय डिकंप्रेशन बीमारी का जोखिम हमेशा रहता है। इस प्लानर का उपयोग अपने जोखिम पर करें। हमेशा सुरक्षित डाइविंग अभ्यासों का पालन करें और पेशेवर डाइव प्रशिक्षकों से सलाह लें।",
        MSG_DEBUG_COPIED: "डीबग जानकारी क्लिपबोर्ड पर कॉपी की गई।",
        MSG_DEBUG_COPY_FAILED: "डीबग जानकारी क्लिपबोर्ड पर कॉपी विफल।",
        MSG_DEBUG_LOADED: "क्लिपबोर्ड से डीबग जानकारी लोड की गई।",
        MSG_DEBUG_LOAD_FAILED: "क्लिपबोर्ड से डीबग जानकारी लोड विफल।",
        UNIT_MIN: "मिन",
        UNIT_BAR: "बार",
        UNIT_PSI: "psi",
        UNIT_CUFT: "घन फीट",
        UNIT_AIR_RATIO: "× वायु",
        ABOUT_MATH_TESTS_FULL: "गणितीय सत्यापन परीक्षण। इंजन को मूल Android MultiDeco बाइनरी (libmultideco.so) के विरुद्ध सत्यापित किया गया है। प्रत्येक गैस मिश्रण उपकरण (Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density) और प्रत्येक डिकंप्रेशन प्रिमिटिव (ZH-L16C Schreiner लोडिंग, Gradient Factor सीलिंग, VPM-B क्रिटिकल वॉल्यूम, CCR सेटपॉइंट, विस्तारित स्टॉप्स, OTU/CNS, ताज़ा/खारा पानी SLP व्यवहार) स्वचालित परीक्षणों द्वारा कवर किया गया है, जिसमें Android संदर्भ मानों के विरुद्ध सहिष्णुता जाँच होती है। आप पूरे टेस्ट सूट को अपने ब्राउज़र में चला सकते हैं:",
        ABOUT_ALGORITHMS_FULL: "Bühlmann ZH-L16C एल्गोरिदम पर आधारित, Gradient Factors के साथ। OC डाइविंग के लिए डिकंप्रेशन योजना लागू करता है। गैस मिश्रण उपकरण शामिल हैं: Best Mix, EAD/MOD, Nitrox, Trimix, Top-up, Capacity, Density।",
        ABOUT_WARNING_TEXT_FULL: "किसी भी डाइव प्रोफ़ाइल के लिए डिकंप्रेशन बीमारी (DCS) का जोखिम हमेशा बना रहता है, भले ही आप डाइव तालिकाओं द्वारा निर्धारित योजना का पालन करें। कोई भी प्रक्रिया या डाइव तालिका DCS या ऑक्सीजन विषाक्तता की संभावना को समाप्त नहीं कर सकती! व्यक्ति की शारीरिक स्थिति दिन-प्रतिदिन बदल सकती है। DCS जोखिम को कम करने के लिए दृढ़ता से सलाह दी जाती है कि योजनाकार द्वारा दी गई एक्सपोज़र सीमाओं के भीतर अच्छी तरह से बने रहें।",
        RESULT_GAS_USAGE: "गैस उपयोग",
        RESULT_TH_VOLUME: "मात्रा",
        RESULT_TH_24Lx2: "24L x2",
        RESULT_PP_TITLE: "गैस आंशिक दाब",
        CHART_XAXIS_RUNTIME: "रनटाइम (मिन)",
        CHART_YAXIS_PRESSURE: "दाब (बार)",
        CHART_COMP: "कक्ष {n}",
        RESULT_GRID_PLAN: "विस्तृत योजना",
        TH_ACTION: "क्रिया",
        TH_DEPTH: "गहराई",
        TH_TIME: "समय",
        TH_RUNTIME: "रनटाइम",
        TH_O2: "O2",
        TH_HE: "He",
        TH_SETPOINT: "सेटपॉइंट",
        TH_PPO2: "pO2",
        TH_EAD: "EAD",
        TH_END: "END",
        TH_CNS: "CNS",
        TH_OTU: "OTU",
        TH_SEG: "सेग",
        TH_GAS: "गैस",
        ACTION_DESCENT: "अवतरण",
        ACTION_LEVEL: "स्तर",
        ACTION_ASCENT: "आरोहण",
        ACTION_STOP: "रुकाव",
        ACTION_SURFACE: "सतह",
        ACTION_STOP_SHORT: "रुक",
        ACTION_DESC_SHORT: "नीचे",
        ACTION_ASC_SHORT: "ऊपर",
        ACTION_BOTTOM_SHORT: "तल",
        ACTION_SURF_SHORT: "सतह",
        RESULT_BAILOUT_PLAN: "बेलआउट योजना — {model}",
        RESULT_BAILOUT_GAS_REQ: "बेलआउट के लिए गैस आवश्यक",
        REPORT_TITLE: "ApexDeco - गोताखोरी योजना",
        REPORT_CIRCUIT: "परिपथ",
        REPORT_MODEL: "मॉडल",
        REPORT_UNITS: "इकाइयाँ",
        REPORT_UNITS_METRIC: "मेट्रिक",
        REPORT_UNITS_IMPERIAL: "इम्पीरियल",
        REPORT_WATER_SALT: "खारा पानी",
        REPORT_WATER_FRESH: "ताज़ा पानी",
        REPORT_BOTTOM_LEVELS: "निचले स्तर:",
        REPORT_DECO_MIXES: "डीको मिश्रण:",
        REPORT_PLAN: "योजना:",
        REPORT_TH_SEGMENT: "खंड",
        REPORT_TH_DEPTH: "गहराई",
        REPORT_TH_TIME: "समय",
        REPORT_TH_RUN: "Run",
        REPORT_TH_GAS: "गैस",
        REPORT_TOTAL_RUNTIME: "कुल समय",
        REPORT_OTU: "OTU",
        REPORT_CNS: "CNS",
        WARN_INVALID_MIX: "अमान्य मिश्रण — मान जाँचें।",
        GAS_TRIMIX: "ट्राइमिक्स",
        GAS_NITROX: "नाइट्रोक्स",
        CONFIRM_RESET: "सभी सेटिंग्स को डिफ़ॉल्ट पर रीसेट करें?",
        UNIT_BAR_OC: "बार (0 = OC)",
        UNIT_MIN_OFF: "मिन (0 = बंद)"
    }
};
